/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpcc_heavy_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_low CASADI_PREFIX(low)
#define casadi_lsqr_single_solve CASADI_PREFIX(lsqr_single_solve)
#define casadi_lsqr_solve CASADI_PREFIX(lsqr_solve)
#define casadi_lsqr_sym_ortho CASADI_PREFIX(lsqr_sym_ortho)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_mv CASADI_PREFIX(mv)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_mv(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, casadi_real* z, casadi_int tr) {
  casadi_int ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!x || !y || !z) return;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el<colind_x[i+1]; ++el) {
        z[i] += x[el] * y[row_x[el]];
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el<colind_x[i+1]; ++el) {
        z[row_x[el]] += x[el] * y[i];
      }
    }
  }
}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

void casadi_lsqr_sym_ortho(casadi_real a, casadi_real b, casadi_real* cs, casadi_real* sn, casadi_real* rho) {
    casadi_real tau;
    if (b == 0) {
        *cs = casadi_sign(a);
        *sn = 0;
        *rho = casadi_fabs(a);
    } else if (a==0) {
        *cs = 0;
        *sn = casadi_sign(b);
        *rho = casadi_fabs(b);
    } else if (casadi_fabs(b)>casadi_fabs(a)) {
        tau = a/b;
        *sn = casadi_sign(b)/sqrt(1+tau*tau);
        *cs = (*sn)*tau;
        *rho = b/(*sn);
    } else {
        tau = b/a;
        *cs = casadi_sign(a)/sqrt(1+tau*tau);
        *sn = (*cs)*tau;
        *rho = a/(*cs);
    }
}
int casadi_lsqr_single_solve(const casadi_real* A, casadi_real* x, casadi_int tr, const casadi_int* sp, casadi_real* w) {
    casadi_int m, n, i;
    casadi_real damp, atol, btol, conlim, ctol, anorm, acond, dampsq, ddnorm, res2, xnorm, xxnorm, z;
    casadi_real cs2, sn2, alpha, beta, rhobar, phibar, bnorm, rnorm, arnorm, rhobar1, cs1, sn1, psi;
    casadi_real cs, sn, rho, theta, phi, tau, t1, t2, n2dk, delta, gambar, rhs, zbar, gamma, res1;
    casadi_real r1sq, r1norm, test1, test2, test3, rtol;
    casadi_int iter_lim, itn, istop;
    casadi_real *u, *v, *xx, *ww, *dk;
    m = sp[0];
    n = sp[1];
    damp = 0;
    atol = 1e-15;
    btol = 1e-15;
    conlim = 1e8;
    iter_lim = 10000;
    itn = 0;
    istop = 0;
    ctol = 0;
    if (conlim > 0) ctol = 1/conlim;
    anorm = 0;
    acond = 0;
    dampsq = damp*damp;
    ddnorm = 0;
    res2 = 0;
    xnorm = 0;
    xxnorm = 0;
    z = 0;
    cs2 = -1;
    sn2 = 0;
    u = w;  w+= m; casadi_copy(x, m, u);
    v = w;  w+= n; casadi_clear(v, n);
    xx = w; w+= n; casadi_clear(xx, n);
    ww = w; w+= n; casadi_clear(v, n);
    dk = w; w+= n;
    alpha = 0;
    beta = casadi_norm_2(m, u);
    if (beta>0) {
      for (i=0;i<m;++i) u[i]*=1/beta;
      casadi_mv(A, sp, u, v, !tr);
      alpha = casadi_norm_2(n, v);
    }
    if (alpha>0) {
      for (i=0;i<n;++i) v[i]*=1/alpha;
      casadi_copy(v, n, ww);
    }
    rhobar = alpha;
    phibar = beta;
    bnorm = beta;
    rnorm = beta;
    arnorm = alpha * beta;
    if (arnorm==0.0) {
      casadi_clear(x, m);
      return 0;
    }
    while (itn<iter_lim) {
      itn++;
      for (i=0;i<m;++i) u[i]*=-alpha;
      casadi_mv(A, sp, v, u, tr);
      beta = casadi_norm_2(m, u);
      if (beta>0) {
        for (i=0;i<m;++i) u[i]*=1/beta;
        anorm = sqrt(anorm*anorm + alpha*alpha+beta*beta+damp*damp);
        for (i=0;i<n;++i) v[i]*=-beta;
        casadi_mv(A, sp, u, v, !tr);
        alpha = casadi_norm_2(n, v);
        if (alpha>0) for (i=0;i<n;++i) v[i]*=1/alpha;
      }
      rhobar1 = sqrt(rhobar*rhobar+damp*damp);
      cs1 = rhobar / rhobar1;
      sn1 = damp / rhobar1;
      psi = sn1 * phibar;
      phibar *= cs1;
      casadi_lsqr_sym_ortho(rhobar1, beta, &cs, &sn, &rho);
      theta = sn * alpha;
      rhobar = -cs * alpha;
      phi = cs * phibar;
      phibar *= sn;
      tau = sn * phi;
      t1 = phi / rho;
      t2 = -theta / rho;
      for (i=0;i<n;++i) dk[i]=ww[i]/rho;
      for (i=0; i<n; ++i) xx[i] += t1*ww[i];
      for (i=0; i<n; ++i) ww[i] = v[i] + t2*ww[i];
      n2dk = casadi_norm_2(n, dk);
      ddnorm += n2dk*n2dk;
      delta = sn2 * rho;
      gambar = -cs2 * rho;
      rhs = phi - delta * z;
      zbar = rhs / gambar;
      xnorm = sqrt(xxnorm + zbar*zbar);
      gamma = sqrt(gambar*gambar + theta*theta);
      cs2 = gambar / gamma;
      sn2 = theta / gamma;
      z = rhs / gamma;
      xxnorm += z*z;
      acond = anorm * sqrt(ddnorm);
      res1 = phibar*phibar;
      res2 += psi*psi;
      rnorm = sqrt(res1+res2);
      arnorm = alpha*casadi_fabs(tau);
      r1sq = rnorm*rnorm - dampsq * xxnorm;
      r1norm = sqrt(casadi_fabs(r1sq));
      if (r1sq < 0) r1norm = -r1norm;
      test1 = rnorm / bnorm;
      test2 = arnorm / (anorm * rnorm);
      test3 = 1 / acond;
      t1 = test1 / (1 + anorm * xnorm / bnorm);
      rtol = btol + atol * anorm * xnorm / bnorm;
      if (itn >= iter_lim) istop = 7;
      if (1 + test3 <= 1) istop = 6;
      if (1 + test2 <= 1) istop = 5;
      if (1 + t1 <= 1) istop = 4;
      if (test3 <= ctol) istop = 3;
      if (test2 <= atol) istop = 2;
      if (test1 <= rtol) istop = 1;
      if (istop != 0) break;
    }
    casadi_copy(xx, m, x);
    return 0;
}
int casadi_lsqr_solve(const casadi_real* A, casadi_real* x, casadi_int nrhs, casadi_int tr,
        const casadi_int* sp, casadi_real* w) {
    casadi_int i;
    for (i=0; i<nrhs;++i) {
      if (casadi_lsqr_single_solve(A, x+i*sp[1], tr, sp, w)) return 1;
    }
    return 0;
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[208] = 
  {41, 41, 0, 2, 5, 9, 14, 18,
  22, 26, 30, 34, 38, 42, 46, 50,
  54, 58, 62, 66, 70, 74, 78, 82,
  86, 90, 94, 98, 102, 106, 110, 114,
  118, 122, 126, 130, 134, 138, 142, 146,
  152, 157, 161, 164, 0, 1, 0, 1,
  2, 0, 1, 2, 3, 0, 1, 2,
  3, 4, 2, 3, 4, 5, 3, 4,
  5, 6, 4, 5, 6, 7, 5, 6,
  7, 8, 6, 7, 8, 9, 7, 8,
  9, 10, 8, 9, 10, 11, 9, 10,
  11, 12, 10, 11, 12, 13, 11, 12,
  13, 14, 12, 13, 14, 15, 13, 14,
  15, 16, 14, 15, 16, 17, 15, 16,
  17, 18, 16, 17, 18, 19, 17, 18,
  19, 20, 18, 19, 20, 21, 19, 20,
  21, 22, 20, 21, 22, 23, 21, 22,
  23, 24, 22, 23, 24, 25, 23, 24,
  25, 26, 24, 25, 26, 27, 25, 26,
  27, 28, 26, 27, 28, 29, 27, 28,
  29, 30, 28, 29, 30, 31, 29, 30,
  31, 32, 30, 31, 32, 33, 31, 32,
  33, 34, 32, 33, 34, 35, 33, 34,
  35, 36, 34, 35, 36, 37, 35, 36,
  37, 38, 39, 40, 36, 37, 38, 39,
  40, 37, 38, 39, 40, 38, 39, 40};
static const casadi_int casadi_s1[83] = 
  {1, 40, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29,
  30, 31, 32, 33, 34, 35, 36, 37,
  38, 39, 40, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0};
static const casadi_int casadi_s2[123] = 
  {41, 40, 0, 2, 4, 6, 8, 10,
  12, 14, 16, 18, 20, 22, 24, 26,
  28, 30, 32, 34, 36, 38, 40, 42,
  44, 46, 48, 50, 52, 54, 56, 58,
  60, 62, 64, 66, 68, 70, 72, 74,
  76, 78, 80, 0, 1, 1, 2, 2,
  3, 3, 4, 4, 5, 5, 6, 6,
  7, 7, 8, 8, 9, 9, 10, 10,
  11, 11, 12, 12, 13, 13, 14, 14,
  15, 15, 16, 16, 17, 17, 18, 18,
  19, 19, 20, 20, 21, 21, 22, 22,
  23, 23, 24, 24, 25, 25, 26, 26,
  27, 27, 28, 28, 29, 29, 30, 30,
  31, 31, 32, 32, 33, 33, 34, 34,
  35, 35, 36, 36, 37, 37, 38, 38,
  39, 39, 40};
static const casadi_int casadi_s3[85] = 
  {1, 41, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29,
  30, 31, 32, 33, 34, 35, 36, 37,
  38, 39, 40, 41, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0};
static const casadi_int casadi_s4[2] = {0, 43};
static const casadi_int casadi_s5[1] = {2};
static const casadi_int casadi_s6[1] = {1};
static const casadi_int casadi_s7[1] = {0};
static const casadi_int casadi_s8[2] = {0, 45};
static const casadi_int casadi_s9[1] = {3};
static const casadi_int casadi_s10[81] = 
  {1, 39, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29,
  30, 31, 32, 33, 34, 35, 36, 37,
  38, 39, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0};
static const casadi_int casadi_s11[120] = 
  {40, 39, 0, 2, 4, 6, 8, 10,
  12, 14, 16, 18, 20, 22, 24, 26,
  28, 30, 32, 34, 36, 38, 40, 42,
  44, 46, 48, 50, 52, 54, 56, 58,
  60, 62, 64, 66, 68, 70, 72, 74,
  76, 78, 0, 1, 1, 2, 2, 3,
  3, 4, 4, 5, 5, 6, 6, 7,
  7, 8, 8, 9, 9, 10, 10, 11,
  11, 12, 12, 13, 13, 14, 14, 15,
  15, 16, 16, 17, 17, 18, 18, 19,
  19, 20, 20, 21, 21, 22, 22, 23,
  23, 24, 24, 25, 25, 26, 26, 27,
  27, 28, 28, 29, 29, 30, 30, 31,
  31, 32, 32, 33, 33, 34, 34, 35,
  35, 36, 36, 37, 37, 38, 38, 39};
static const casadi_int casadi_s12[2] = {0, 41};
static const casadi_int casadi_s13[3] = {13, 1, 1};
static const casadi_int casadi_s14[3] = {7, 1, 1};
static const casadi_int casadi_s15[3] = {0, 1, 1};
static const casadi_int casadi_s16[3] = {16, 1, 1};
static const casadi_int casadi_s17[3] = {0, 0, 1};
static const casadi_int casadi_s18[3] = {213, 1, 1};
static const casadi_int casadi_s19[28] = 
  {20, 20, 0, 0, 0, 0, 0, 0,
  0, 0, 1, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 5, 19,
  19, 7, 8, 19};

static const casadi_real casadi_c0[164] = 
  {1., 1.2500000000000000e-01, 0., 5.1388888888888895e-01, 1.1111111111111113e-01, 0., 3.1944444444444442e-01, 5.5555555555555558e-01,
  1.2499999999999993e-01, 0., 4.1666666666666664e-02, 3.3333333333333331e-01, 7.0833333333333326e-01, 1.6666666666666663e-01, 0., 1.6666666666666677e-01,
  6.6666666666666674e-01, 1.6666666666666685e-01, 0., 1.6666666666666660e-01, 6.6666666666666652e-01, 1.6666666666666652e-01, 0., 1.6666666666666652e-01,
  6.6666666666666652e-01, 1.6666666666666660e-01, 0., 1.6666666666666685e-01, 6.6666666666666674e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01,
  6.6666666666666663e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01, 6.6666666666666674e-01, 1.6666666666666685e-01, 0., 1.6666666666666660e-01,
  6.6666666666666663e-01, 1.6666666666666674e-01, 0., 1.6666666666666646e-01, 6.6666666666666652e-01, 1.6666666666666624e-01, 0., 1.6666666666666680e-01,
  6.6666666666666674e-01, 1.6666666666666696e-01, 0., 1.6666666666666696e-01, 6.6666666666666674e-01, 1.6666666666666635e-01, 0., 1.6666666666666635e-01,
  6.6666666666666674e-01, 1.6666666666666696e-01, 0., 1.6666666666666696e-01, 6.6666666666666674e-01, 1.6666666666666680e-01, 0., 1.6666666666666624e-01,
  6.6666666666666641e-01, 1.6666666666666624e-01, 0., 1.6666666666666680e-01, 6.6666666666666674e-01, 1.6666666666666696e-01, 0., 1.6666666666666696e-01,
  6.6666666666666674e-01, 1.6666666666666635e-01, 0., 1.6666666666666635e-01, 6.6666666666666674e-01, 1.6666666666666696e-01, 0., 1.6666666666666696e-01,
  6.6666666666666674e-01, 1.6666666666666680e-01, 0., 1.6666666666666624e-01, 6.6666666666666652e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01,
  6.6666666666666663e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01, 6.6666666666666641e-01, 1.6666666666666580e-01, 0., 1.6666666666666691e-01,
  6.6666666666666696e-01, 1.6666666666666730e-01, 0., 1.6666666666666730e-01, 6.6666666666666696e-01, 1.6666666666666691e-01, 0., 1.6666666666666580e-01,
  6.6666666666666641e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01, 6.6666666666666663e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01,
  6.6666666666666641e-01, 1.6666666666666580e-01, 0., 1.6666666666666691e-01, 6.6666666666666696e-01, 1.6666666666666730e-01, 0., 1.6666666666666730e-01,
  6.6666666666666696e-01, 1.6666666666666691e-01, 0., 1.6666666666666580e-01, 6.6666666666666641e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01,
  6.6666666666666663e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01, 6.6666666666666641e-01, 1.6666666666666580e-01, 0., 1.6666666666666691e-01,
  6.6666666666666696e-01, 1.6666666666666730e-01, 0., 1.6666666666666730e-01, 6.6666666666666696e-01, 1.6666666666666691e-01, 0., 1.6666666666666580e-01,
  6.6666666666666641e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01, 7.0833333333333315e-01, 3.3333333333333270e-01, 4.1666666666666310e-02, 0.,
  0., 1.2500000000000014e-01, 5.5555555555555591e-01, 3.1944444444444325e-01, 0., 0., 1.1111111111111142e-01, 5.1388888888888951e-01,
  0., 0., 1.2500000000000083e-01, 1.};
static const casadi_real casadi_c1[80] = 
  {-60., 60., -40., 40., -30., 30., -40., 40.,
  -40., 40., -40., 40., -40., 40., -4.0000000000000007e+01, 4.0000000000000007e+01,
  -4.0000000000000007e+01, 4.0000000000000007e+01, -40., 40., -3.9999999999999979e+01, 3.9999999999999979e+01, -40., 40.,
  -40., 40., -4.0000000000000021e+01, 4.0000000000000021e+01, -40., 40., -40., 40.,
  -40., 40., -40., 40., -4.0000000000000021e+01, 4.0000000000000021e+01, -40., 40.,
  -40., 40., -3.9999999999999964e+01, 3.9999999999999964e+01, -3.9999999999999964e+01, 3.9999999999999964e+01, -4.0000000000000021e+01, 4.0000000000000021e+01,
  -4.0000000000000021e+01, 4.0000000000000021e+01, -4.0000000000000021e+01, 4.0000000000000021e+01, -3.9999999999999964e+01, 3.9999999999999964e+01, -3.9999999999999964e+01, 3.9999999999999964e+01,
  -4.0000000000000021e+01, 4.0000000000000021e+01, -4.0000000000000021e+01, 4.0000000000000021e+01, -4.0000000000000021e+01, 4.0000000000000021e+01, -3.9999999999999964e+01, 3.9999999999999964e+01,
  -3.9999999999999964e+01, 3.9999999999999964e+01, -4.0000000000000021e+01, 4.0000000000000021e+01, -4.0000000000000021e+01, 4.0000000000000021e+01, -4.0000000000000021e+01, 4.0000000000000021e+01,
  -3.9999999999999964e+01, 3.9999999999999964e+01, -3.0000000000000007e+01, 3.0000000000000007e+01, -4.0000000000000021e+01, 4.0000000000000021e+01, -6.0000000000000085e+01, 6.0000000000000085e+01};
static const casadi_real casadi_c2[43] = 
  {0., 0., 0., 5.0000000000000003e-02, 7.5000000000000011e-02, 1.0000000000000001e-01, 1.2500000000000000e-01, 1.5000000000000002e-01,
  1.7500000000000002e-01, 2.0000000000000001e-01, 2.2500000000000001e-01, 2.5000000000000000e-01, 2.7500000000000002e-01, 3.0000000000000004e-01, 3.2500000000000001e-01, 3.5000000000000003e-01,
  3.7500000000000000e-01, 4.0000000000000002e-01, 4.2500000000000004e-01, 4.5000000000000001e-01, 4.7500000000000003e-01, 5.0000000000000000e-01, 5.2500000000000002e-01, 5.5000000000000004e-01,
  5.7500000000000007e-01, 6.0000000000000009e-01, 6.2500000000000000e-01, 6.5000000000000002e-01, 6.7500000000000004e-01, 7.0000000000000007e-01, 7.2500000000000009e-01, 7.5000000000000000e-01,
  7.7500000000000002e-01, 8.0000000000000004e-01, 8.2500000000000007e-01, 8.5000000000000009e-01, 8.7500000000000000e-01, 9.0000000000000002e-01, 9.2500000000000004e-01, 9.5000000000000007e-01,
  1., 1., 1.};
static const casadi_real casadi_c3[45] = 
  {0., 0., 0., 0., 5.0000000000000003e-02, 7.5000000000000011e-02, 1.0000000000000001e-01, 1.2500000000000000e-01,
  1.5000000000000002e-01, 1.7500000000000002e-01, 2.0000000000000001e-01, 2.2500000000000001e-01, 2.5000000000000000e-01, 2.7500000000000002e-01, 3.0000000000000004e-01, 3.2500000000000001e-01,
  3.5000000000000003e-01, 3.7500000000000000e-01, 4.0000000000000002e-01, 4.2500000000000004e-01, 4.5000000000000001e-01, 4.7500000000000003e-01, 5.0000000000000000e-01, 5.2500000000000002e-01,
  5.5000000000000004e-01, 5.7500000000000007e-01, 6.0000000000000009e-01, 6.2500000000000000e-01, 6.5000000000000002e-01, 6.7500000000000004e-01, 7.0000000000000007e-01, 7.2500000000000009e-01,
  7.5000000000000000e-01, 7.7500000000000002e-01, 8.0000000000000004e-01, 8.2500000000000007e-01, 8.5000000000000009e-01, 8.7500000000000000e-01, 9.0000000000000002e-01, 9.2500000000000004e-01,
  9.5000000000000007e-01, 1., 1., 1., 1.};
static const casadi_real casadi_c4[78] = 
  {-40., 40., -2.6666666666666664e+01, 2.6666666666666664e+01, -40., 40., -4.0000000000000007e+01, 4.0000000000000007e+01,
  -3.9999999999999986e+01, 3.9999999999999986e+01, -3.9999999999999986e+01, 3.9999999999999986e+01, -4.0000000000000007e+01, 4.0000000000000007e+01, -4.0000000000000007e+01, 4.0000000000000007e+01,
  -4.0000000000000007e+01, 4.0000000000000007e+01, -3.9999999999999986e+01, 3.9999999999999986e+01, -3.9999999999999964e+01, 3.9999999999999964e+01, -4.0000000000000007e+01, 4.0000000000000007e+01,
  -4.0000000000000007e+01, 4.0000000000000007e+01, -4.0000000000000007e+01, 4.0000000000000007e+01, -4.0000000000000007e+01, 4.0000000000000007e+01, -3.9999999999999964e+01, 3.9999999999999964e+01,
  -4.0000000000000007e+01, 4.0000000000000007e+01, -4.0000000000000007e+01, 4.0000000000000007e+01, -4.0000000000000007e+01, 4.0000000000000007e+01, -4.0000000000000007e+01, 4.0000000000000007e+01,
  -3.9999999999999964e+01, 3.9999999999999964e+01, -3.9999999999999964e+01, 3.9999999999999964e+01, -3.9999999999999964e+01, 3.9999999999999964e+01, -4.0000000000000057e+01, 4.0000000000000057e+01,
  -4.0000000000000057e+01, 4.0000000000000057e+01, -3.9999999999999964e+01, 3.9999999999999964e+01, -3.9999999999999964e+01, 3.9999999999999964e+01, -3.9999999999999964e+01, 3.9999999999999964e+01,
  -4.0000000000000057e+01, 4.0000000000000057e+01, -4.0000000000000057e+01, 4.0000000000000057e+01, -3.9999999999999964e+01, 3.9999999999999964e+01, -3.9999999999999964e+01, 3.9999999999999964e+01,
  -3.9999999999999964e+01, 3.9999999999999964e+01, -4.0000000000000057e+01, 4.0000000000000057e+01, -4.0000000000000057e+01, 4.0000000000000057e+01, -3.9999999999999964e+01, 3.9999999999999964e+01,
  -3.9999999999999964e+01, 3.9999999999999964e+01, -2.6666666666666682e+01, 2.6666666666666682e+01, -4.0000000000000057e+01, 4.0000000000000057e+01};
static const casadi_real casadi_c5[41] = 
  {0., 0., 5.0000000000000003e-02, 7.5000000000000011e-02, 1.0000000000000001e-01, 1.2500000000000000e-01, 1.5000000000000002e-01, 1.7500000000000002e-01,
  2.0000000000000001e-01, 2.2500000000000001e-01, 2.5000000000000000e-01, 2.7500000000000002e-01, 3.0000000000000004e-01, 3.2500000000000001e-01, 3.5000000000000003e-01, 3.7500000000000000e-01,
  4.0000000000000002e-01, 4.2500000000000004e-01, 4.5000000000000001e-01, 4.7500000000000003e-01, 5.0000000000000000e-01, 5.2500000000000002e-01, 5.5000000000000004e-01, 5.7500000000000007e-01,
  6.0000000000000009e-01, 6.2500000000000000e-01, 6.5000000000000002e-01, 6.7500000000000004e-01, 7.0000000000000007e-01, 7.2500000000000009e-01, 7.5000000000000000e-01, 7.7500000000000002e-01,
  8.0000000000000004e-01, 8.2500000000000007e-01, 8.5000000000000009e-01, 8.7500000000000000e-01, 9.0000000000000002e-01, 9.2500000000000004e-01, 9.5000000000000007e-01, 1.,
  1.};

static const casadi_real casadi_zeros[41] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* fwd1_mpcc_ch:(x,c[41],out_f[1x1,0nz],fwd_x,fwd_c[41])->(fwd_f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, *w1=w+42, *w2=w+82, w5;
  const casadi_real *ss, *wr2, *wr3, *wr4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x40) */
  casadi_clear(w1, 40);
  /* #2: @2 = input[1][0] */
  wr2 = arg[1] ? arg[1] : casadi_zeros;
  /* #3: @3 = sparse: 41-by-41, 164 nnz
   (0, 0) -> 1
   (1, 0) -> 0.125
   (0, 1) -> 0
   (1, 1) -> 0.513889
   (2, 1) -> 0.111111
   (0, 2) -> 0
   (1, 2) -> 0.319444
   (2, 2) -> 0.555556
   (3, 2) -> 0.125
   (0, 3) -> 0
   (1, 3) -> 0.0416667
   (2, 3) -> 0.333333
   (3, 3) -> 0.708333
   (4, 3) -> 0.166667
   (2, 4) -> 0
   (3, 4) -> 0.166667
   (4, 4) -> 0.666667
   (5, 4) -> 0.166667
   (3, 5) -> 0
   (4, 5) -> 0.166667
   (5, 5) -> 0.666667
   (6, 5) -> 0.166667
   (4, 6) -> 0
   (5, 6) -> 0.166667
   (6, 6) -> 0.666667
   (7, 6) -> 0.166667
   (5, 7) -> 0
   (6, 7) -> 0.166667
   (7, 7) -> 0.666667
   (8, 7) -> 0.166667
   (6, 8) -> 0
   (7, 8) -> 0.166667
   (8, 8) -> 0.666667
   (9, 8) -> 0.166667
   (7, 9) -> 0
   (8, 9) -> 0.166667
   (9, 9) -> 0.666667
   (10, 9) -> 0.166667
   (8, 10) -> 0
   (9, 10) -> 0.166667
   (10, 10) -> 0.666667
   (11, 10) -> 0.166667
   (9, 11) -> 0
   (10, 11) -> 0.166667
   (11, 11) -> 0.666667
   (12, 11) -> 0.166667
   (10, 12) -> 0
   (11, 12) -> 0.166667
   (12, 12) -> 0.666667
   (13, 12) -> 0.166667
   (11, 13) -> 0
   (12, 13) -> 0.166667
   (13, 13) -> 0.666667
   (14, 13) -> 0.166667
   (12, 14) -> 0
   (13, 14) -> 0.166667
   (14, 14) -> 0.666667
   (15, 14) -> 0.166667
   (13, 15) -> 0
   (14, 15) -> 0.166667
   (15, 15) -> 0.666667
   (16, 15) -> 0.166667
   (14, 16) -> 0
   (15, 16) -> 0.166667
   (16, 16) -> 0.666667
   (17, 16) -> 0.166667
   (15, 17) -> 0
   (16, 17) -> 0.166667
   (17, 17) -> 0.666667
   (18, 17) -> 0.166667
   (16, 18) -> 0
   (17, 18) -> 0.166667
   (18, 18) -> 0.666667
   (19, 18) -> 0.166667
   (17, 19) -> 0
   (18, 19) -> 0.166667
   (19, 19) -> 0.666667
   (20, 19) -> 0.166667
   (18, 20) -> 0
   (19, 20) -> 0.166667
   (20, 20) -> 0.666667
   (21, 20) -> 0.166667
   (19, 21) -> 0
   (20, 21) -> 0.166667
   (21, 21) -> 0.666667
   (22, 21) -> 0.166667
   (20, 22) -> 0
   (21, 22) -> 0.166667
   (22, 22) -> 0.666667
   (23, 22) -> 0.166667
   (21, 23) -> 0
   (22, 23) -> 0.166667
   (23, 23) -> 0.666667
   (24, 23) -> 0.166667
   (22, 24) -> 0
   (23, 24) -> 0.166667
   (24, 24) -> 0.666667
   (25, 24) -> 0.166667
   (23, 25) -> 0
   (24, 25) -> 0.166667
   (25, 25) -> 0.666667
   (26, 25) -> 0.166667
   (24, 26) -> 0
   (25, 26) -> 0.166667
   (26, 26) -> 0.666667
   (27, 26) -> 0.166667
   (25, 27) -> 0
   (26, 27) -> 0.166667
   (27, 27) -> 0.666667
   (28, 27) -> 0.166667
   (26, 28) -> 0
   (27, 28) -> 0.166667
   (28, 28) -> 0.666667
   (29, 28) -> 0.166667
   (27, 29) -> 0
   (28, 29) -> 0.166667
   (29, 29) -> 0.666667
   (30, 29) -> 0.166667
   (28, 30) -> 0
   (29, 30) -> 0.166667
   (30, 30) -> 0.666667
   (31, 30) -> 0.166667
   (29, 31) -> 0
   (30, 31) -> 0.166667
   (31, 31) -> 0.666667
   (32, 31) -> 0.166667
   (30, 32) -> 0
   (31, 32) -> 0.166667
   (32, 32) -> 0.666667
   (33, 32) -> 0.166667
   (31, 33) -> 0
   (32, 33) -> 0.166667
   (33, 33) -> 0.666667
   (34, 33) -> 0.166667
   (32, 34) -> 0
   (33, 34) -> 0.166667
   (34, 34) -> 0.666667
   (35, 34) -> 0.166667
   (33, 35) -> 0
   (34, 35) -> 0.166667
   (35, 35) -> 0.666667
   (36, 35) -> 0.166667
   (34, 36) -> 0
   (35, 36) -> 0.166667
   (36, 36) -> 0.666667
   (37, 36) -> 0.166667
   (35, 37) -> 0
   (36, 37) -> 0.166667
   (37, 37) -> 0.708333
   (38, 37) -> 0.333333
   (39, 37) -> 0.0416667
   (40, 37) -> 0
   (36, 38) -> 0
   (37, 38) -> 0.125
   (38, 38) -> 0.555556
   (39, 38) -> 0.319444
   (40, 38) -> 0
   (37, 39) -> 0
   (38, 39) -> 0.111111
   (39, 39) -> 0.513889
   (40, 39) -> 0
   (38, 40) -> 0
   (39, 40) -> 0.125
   (40, 40) -> 1 */
  wr3 = casadi_c0;
  /* #4: @2 = (@3\@2) */
  rr = w2;
  ss = wr3;
  casadi_copy(wr2, 41, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real w[205];
    casadi_lsqr_solve(ss, rr, 1, 0, casadi_s0, w);
  }
  /* #5: @2 = @2' */
  /* #6: @4 = sparse: 41-by-40, 80 nnz
   (0, 0) -> -60
   (1, 0) -> 60
   (1, 1) -> -40
   (2, 1) -> 40
   (2, 2) -> -30
   (3, 2) -> 30
   (3, 3) -> -40
   (4, 3) -> 40
   (4, 4) -> -40
   (5, 4) -> 40
   (5, 5) -> -40
   (6, 5) -> 40
   (6, 6) -> -40
   (7, 6) -> 40
   (7, 7) -> -40
   (8, 7) -> 40
   (8, 8) -> -40
   (9, 8) -> 40
   (9, 9) -> -40
   (10, 9) -> 40
   (10, 10) -> -40
   (11, 10) -> 40
   (11, 11) -> -40
   (12, 11) -> 40
   (12, 12) -> -40
   (13, 12) -> 40
   (13, 13) -> -40
   (14, 13) -> 40
   (14, 14) -> -40
   (15, 14) -> 40
   (15, 15) -> -40
   (16, 15) -> 40
   (16, 16) -> -40
   (17, 16) -> 40
   (17, 17) -> -40
   (18, 17) -> 40
   (18, 18) -> -40
   (19, 18) -> 40
   (19, 19) -> -40
   (20, 19) -> 40
   (20, 20) -> -40
   (21, 20) -> 40
   (21, 21) -> -40
   (22, 21) -> 40
   (22, 22) -> -40
   (23, 22) -> 40
   (23, 23) -> -40
   (24, 23) -> 40
   (24, 24) -> -40
   (25, 24) -> 40
   (25, 25) -> -40
   (26, 25) -> 40
   (26, 26) -> -40
   (27, 26) -> 40
   (27, 27) -> -40
   (28, 27) -> 40
   (28, 28) -> -40
   (29, 28) -> 40
   (29, 29) -> -40
   (30, 29) -> 40
   (30, 30) -> -40
   (31, 30) -> 40
   (31, 31) -> -40
   (32, 31) -> 40
   (32, 32) -> -40
   (33, 32) -> 40
   (33, 33) -> -40
   (34, 33) -> 40
   (34, 34) -> -40
   (35, 34) -> 40
   (35, 35) -> -40
   (36, 35) -> 40
   (36, 36) -> -40
   (37, 36) -> 40
   (37, 37) -> -30
   (38, 37) -> 30
   (38, 38) -> -40
   (39, 38) -> 40
   (39, 39) -> -60
   (40, 39) -> 60 */
  wr4 = casadi_c1;
  /* #7: @1 = mac(@2,@4,@1) */
  casadi_mtimes(w2, casadi_s3, wr4, casadi_s2, w1, casadi_s1, w, 0);
  /* #8: @5 = BSplineParametric(@0, @1) */
  casadi_clear((&w5), 1);
  CASADI_PREFIX(nd_boor_eval)((&w5),1,casadi_c2,casadi_s4,casadi_s5,casadi_s6,w1,1,(&w0),casadi_s7, iw, w);
  /* #9: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #10: @5 = (@5*@0) */
  w5 *= w0;
  /* #11: output[0][0] = @5 */
  if (res[0]) res[0][0] = w5;
  return 0;
}

/* mpcc_ch:(x,c[41])->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, *w1=w+42, w3;
  const casadi_real *ss, *wr1, *wr2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  wr1 = arg[1] ? arg[1] : casadi_zeros;
  /* #2: @2 = sparse: 41-by-41, 164 nnz
   (0, 0) -> 1
   (1, 0) -> 0.125
   (0, 1) -> 0
   (1, 1) -> 0.513889
   (2, 1) -> 0.111111
   (0, 2) -> 0
   (1, 2) -> 0.319444
   (2, 2) -> 0.555556
   (3, 2) -> 0.125
   (0, 3) -> 0
   (1, 3) -> 0.0416667
   (2, 3) -> 0.333333
   (3, 3) -> 0.708333
   (4, 3) -> 0.166667
   (2, 4) -> 0
   (3, 4) -> 0.166667
   (4, 4) -> 0.666667
   (5, 4) -> 0.166667
   (3, 5) -> 0
   (4, 5) -> 0.166667
   (5, 5) -> 0.666667
   (6, 5) -> 0.166667
   (4, 6) -> 0
   (5, 6) -> 0.166667
   (6, 6) -> 0.666667
   (7, 6) -> 0.166667
   (5, 7) -> 0
   (6, 7) -> 0.166667
   (7, 7) -> 0.666667
   (8, 7) -> 0.166667
   (6, 8) -> 0
   (7, 8) -> 0.166667
   (8, 8) -> 0.666667
   (9, 8) -> 0.166667
   (7, 9) -> 0
   (8, 9) -> 0.166667
   (9, 9) -> 0.666667
   (10, 9) -> 0.166667
   (8, 10) -> 0
   (9, 10) -> 0.166667
   (10, 10) -> 0.666667
   (11, 10) -> 0.166667
   (9, 11) -> 0
   (10, 11) -> 0.166667
   (11, 11) -> 0.666667
   (12, 11) -> 0.166667
   (10, 12) -> 0
   (11, 12) -> 0.166667
   (12, 12) -> 0.666667
   (13, 12) -> 0.166667
   (11, 13) -> 0
   (12, 13) -> 0.166667
   (13, 13) -> 0.666667
   (14, 13) -> 0.166667
   (12, 14) -> 0
   (13, 14) -> 0.166667
   (14, 14) -> 0.666667
   (15, 14) -> 0.166667
   (13, 15) -> 0
   (14, 15) -> 0.166667
   (15, 15) -> 0.666667
   (16, 15) -> 0.166667
   (14, 16) -> 0
   (15, 16) -> 0.166667
   (16, 16) -> 0.666667
   (17, 16) -> 0.166667
   (15, 17) -> 0
   (16, 17) -> 0.166667
   (17, 17) -> 0.666667
   (18, 17) -> 0.166667
   (16, 18) -> 0
   (17, 18) -> 0.166667
   (18, 18) -> 0.666667
   (19, 18) -> 0.166667
   (17, 19) -> 0
   (18, 19) -> 0.166667
   (19, 19) -> 0.666667
   (20, 19) -> 0.166667
   (18, 20) -> 0
   (19, 20) -> 0.166667
   (20, 20) -> 0.666667
   (21, 20) -> 0.166667
   (19, 21) -> 0
   (20, 21) -> 0.166667
   (21, 21) -> 0.666667
   (22, 21) -> 0.166667
   (20, 22) -> 0
   (21, 22) -> 0.166667
   (22, 22) -> 0.666667
   (23, 22) -> 0.166667
   (21, 23) -> 0
   (22, 23) -> 0.166667
   (23, 23) -> 0.666667
   (24, 23) -> 0.166667
   (22, 24) -> 0
   (23, 24) -> 0.166667
   (24, 24) -> 0.666667
   (25, 24) -> 0.166667
   (23, 25) -> 0
   (24, 25) -> 0.166667
   (25, 25) -> 0.666667
   (26, 25) -> 0.166667
   (24, 26) -> 0
   (25, 26) -> 0.166667
   (26, 26) -> 0.666667
   (27, 26) -> 0.166667
   (25, 27) -> 0
   (26, 27) -> 0.166667
   (27, 27) -> 0.666667
   (28, 27) -> 0.166667
   (26, 28) -> 0
   (27, 28) -> 0.166667
   (28, 28) -> 0.666667
   (29, 28) -> 0.166667
   (27, 29) -> 0
   (28, 29) -> 0.166667
   (29, 29) -> 0.666667
   (30, 29) -> 0.166667
   (28, 30) -> 0
   (29, 30) -> 0.166667
   (30, 30) -> 0.666667
   (31, 30) -> 0.166667
   (29, 31) -> 0
   (30, 31) -> 0.166667
   (31, 31) -> 0.666667
   (32, 31) -> 0.166667
   (30, 32) -> 0
   (31, 32) -> 0.166667
   (32, 32) -> 0.666667
   (33, 32) -> 0.166667
   (31, 33) -> 0
   (32, 33) -> 0.166667
   (33, 33) -> 0.666667
   (34, 33) -> 0.166667
   (32, 34) -> 0
   (33, 34) -> 0.166667
   (34, 34) -> 0.666667
   (35, 34) -> 0.166667
   (33, 35) -> 0
   (34, 35) -> 0.166667
   (35, 35) -> 0.666667
   (36, 35) -> 0.166667
   (34, 36) -> 0
   (35, 36) -> 0.166667
   (36, 36) -> 0.666667
   (37, 36) -> 0.166667
   (35, 37) -> 0
   (36, 37) -> 0.166667
   (37, 37) -> 0.708333
   (38, 37) -> 0.333333
   (39, 37) -> 0.0416667
   (40, 37) -> 0
   (36, 38) -> 0
   (37, 38) -> 0.125
   (38, 38) -> 0.555556
   (39, 38) -> 0.319444
   (40, 38) -> 0
   (37, 39) -> 0
   (38, 39) -> 0.111111
   (39, 39) -> 0.513889
   (40, 39) -> 0
   (38, 40) -> 0
   (39, 40) -> 0.125
   (40, 40) -> 1 */
  wr2 = casadi_c0;
  /* #3: @1 = (@2\@1) */
  rr = w1;
  ss = wr2;
  casadi_copy(wr1, 41, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real w[205];
    casadi_lsqr_solve(ss, rr, 1, 0, casadi_s0, w);
  }
  /* #4: @1 = @1' */
  /* #5: @3 = BSplineParametric(@0, @1) */
  casadi_clear((&w3), 1);
  CASADI_PREFIX(nd_boor_eval)((&w3),1,casadi_c3,casadi_s8,casadi_s9,casadi_s6,w1,1,(&w0),casadi_s7, iw, w);
  /* #6: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

/* fwd1_adj1_mpcc_ch:(x,c[41],out_f[1x1,0nz],adj_f,out_adj_x[1x1,0nz],out_adj_c[41x1,0nz],fwd_x,fwd_c[41],fwd_out_f[1x1,0nz],fwd_adj_f)->(fwd_adj_x,fwd_adj_c[41x1,0nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, w1, *w2=w+43, *w3=w+82, *w4=w+122, w8, w9;
  const casadi_real *ss, *wr4, *wr5, *wr6, *wr7;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x39) */
  casadi_clear(w2, 39);
  /* #3: @3 = zeros(1x40) */
  casadi_clear(w3, 40);
  /* #4: @4 = input[1][0] */
  wr4 = arg[1] ? arg[1] : casadi_zeros;
  /* #5: @5 = sparse: 41-by-41, 164 nnz
   (0, 0) -> 1
   (1, 0) -> 0.125
   (0, 1) -> 0
   (1, 1) -> 0.513889
   (2, 1) -> 0.111111
   (0, 2) -> 0
   (1, 2) -> 0.319444
   (2, 2) -> 0.555556
   (3, 2) -> 0.125
   (0, 3) -> 0
   (1, 3) -> 0.0416667
   (2, 3) -> 0.333333
   (3, 3) -> 0.708333
   (4, 3) -> 0.166667
   (2, 4) -> 0
   (3, 4) -> 0.166667
   (4, 4) -> 0.666667
   (5, 4) -> 0.166667
   (3, 5) -> 0
   (4, 5) -> 0.166667
   (5, 5) -> 0.666667
   (6, 5) -> 0.166667
   (4, 6) -> 0
   (5, 6) -> 0.166667
   (6, 6) -> 0.666667
   (7, 6) -> 0.166667
   (5, 7) -> 0
   (6, 7) -> 0.166667
   (7, 7) -> 0.666667
   (8, 7) -> 0.166667
   (6, 8) -> 0
   (7, 8) -> 0.166667
   (8, 8) -> 0.666667
   (9, 8) -> 0.166667
   (7, 9) -> 0
   (8, 9) -> 0.166667
   (9, 9) -> 0.666667
   (10, 9) -> 0.166667
   (8, 10) -> 0
   (9, 10) -> 0.166667
   (10, 10) -> 0.666667
   (11, 10) -> 0.166667
   (9, 11) -> 0
   (10, 11) -> 0.166667
   (11, 11) -> 0.666667
   (12, 11) -> 0.166667
   (10, 12) -> 0
   (11, 12) -> 0.166667
   (12, 12) -> 0.666667
   (13, 12) -> 0.166667
   (11, 13) -> 0
   (12, 13) -> 0.166667
   (13, 13) -> 0.666667
   (14, 13) -> 0.166667
   (12, 14) -> 0
   (13, 14) -> 0.166667
   (14, 14) -> 0.666667
   (15, 14) -> 0.166667
   (13, 15) -> 0
   (14, 15) -> 0.166667
   (15, 15) -> 0.666667
   (16, 15) -> 0.166667
   (14, 16) -> 0
   (15, 16) -> 0.166667
   (16, 16) -> 0.666667
   (17, 16) -> 0.166667
   (15, 17) -> 0
   (16, 17) -> 0.166667
   (17, 17) -> 0.666667
   (18, 17) -> 0.166667
   (16, 18) -> 0
   (17, 18) -> 0.166667
   (18, 18) -> 0.666667
   (19, 18) -> 0.166667
   (17, 19) -> 0
   (18, 19) -> 0.166667
   (19, 19) -> 0.666667
   (20, 19) -> 0.166667
   (18, 20) -> 0
   (19, 20) -> 0.166667
   (20, 20) -> 0.666667
   (21, 20) -> 0.166667
   (19, 21) -> 0
   (20, 21) -> 0.166667
   (21, 21) -> 0.666667
   (22, 21) -> 0.166667
   (20, 22) -> 0
   (21, 22) -> 0.166667
   (22, 22) -> 0.666667
   (23, 22) -> 0.166667
   (21, 23) -> 0
   (22, 23) -> 0.166667
   (23, 23) -> 0.666667
   (24, 23) -> 0.166667
   (22, 24) -> 0
   (23, 24) -> 0.166667
   (24, 24) -> 0.666667
   (25, 24) -> 0.166667
   (23, 25) -> 0
   (24, 25) -> 0.166667
   (25, 25) -> 0.666667
   (26, 25) -> 0.166667
   (24, 26) -> 0
   (25, 26) -> 0.166667
   (26, 26) -> 0.666667
   (27, 26) -> 0.166667
   (25, 27) -> 0
   (26, 27) -> 0.166667
   (27, 27) -> 0.666667
   (28, 27) -> 0.166667
   (26, 28) -> 0
   (27, 28) -> 0.166667
   (28, 28) -> 0.666667
   (29, 28) -> 0.166667
   (27, 29) -> 0
   (28, 29) -> 0.166667
   (29, 29) -> 0.666667
   (30, 29) -> 0.166667
   (28, 30) -> 0
   (29, 30) -> 0.166667
   (30, 30) -> 0.666667
   (31, 30) -> 0.166667
   (29, 31) -> 0
   (30, 31) -> 0.166667
   (31, 31) -> 0.666667
   (32, 31) -> 0.166667
   (30, 32) -> 0
   (31, 32) -> 0.166667
   (32, 32) -> 0.666667
   (33, 32) -> 0.166667
   (31, 33) -> 0
   (32, 33) -> 0.166667
   (33, 33) -> 0.666667
   (34, 33) -> 0.166667
   (32, 34) -> 0
   (33, 34) -> 0.166667
   (34, 34) -> 0.666667
   (35, 34) -> 0.166667
   (33, 35) -> 0
   (34, 35) -> 0.166667
   (35, 35) -> 0.666667
   (36, 35) -> 0.166667
   (34, 36) -> 0
   (35, 36) -> 0.166667
   (36, 36) -> 0.666667
   (37, 36) -> 0.166667
   (35, 37) -> 0
   (36, 37) -> 0.166667
   (37, 37) -> 0.708333
   (38, 37) -> 0.333333
   (39, 37) -> 0.0416667
   (40, 37) -> 0
   (36, 38) -> 0
   (37, 38) -> 0.125
   (38, 38) -> 0.555556
   (39, 38) -> 0.319444
   (40, 38) -> 0
   (37, 39) -> 0
   (38, 39) -> 0.111111
   (39, 39) -> 0.513889
   (40, 39) -> 0
   (38, 40) -> 0
   (39, 40) -> 0.125
   (40, 40) -> 1 */
  wr5 = casadi_c0;
  /* #6: @4 = (@5\@4) */
  rr = w4;
  ss = wr5;
  casadi_copy(wr4, 41, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real w[205];
    casadi_lsqr_solve(ss, rr, 1, 0, casadi_s0, w);
  }
  /* #7: @4 = @4' */
  /* #8: @6 = sparse: 41-by-40, 80 nnz
   (0, 0) -> -60
   (1, 0) -> 60
   (1, 1) -> -40
   (2, 1) -> 40
   (2, 2) -> -30
   (3, 2) -> 30
   (3, 3) -> -40
   (4, 3) -> 40
   (4, 4) -> -40
   (5, 4) -> 40
   (5, 5) -> -40
   (6, 5) -> 40
   (6, 6) -> -40
   (7, 6) -> 40
   (7, 7) -> -40
   (8, 7) -> 40
   (8, 8) -> -40
   (9, 8) -> 40
   (9, 9) -> -40
   (10, 9) -> 40
   (10, 10) -> -40
   (11, 10) -> 40
   (11, 11) -> -40
   (12, 11) -> 40
   (12, 12) -> -40
   (13, 12) -> 40
   (13, 13) -> -40
   (14, 13) -> 40
   (14, 14) -> -40
   (15, 14) -> 40
   (15, 15) -> -40
   (16, 15) -> 40
   (16, 16) -> -40
   (17, 16) -> 40
   (17, 17) -> -40
   (18, 17) -> 40
   (18, 18) -> -40
   (19, 18) -> 40
   (19, 19) -> -40
   (20, 19) -> 40
   (20, 20) -> -40
   (21, 20) -> 40
   (21, 21) -> -40
   (22, 21) -> 40
   (22, 22) -> -40
   (23, 22) -> 40
   (23, 23) -> -40
   (24, 23) -> 40
   (24, 24) -> -40
   (25, 24) -> 40
   (25, 25) -> -40
   (26, 25) -> 40
   (26, 26) -> -40
   (27, 26) -> 40
   (27, 27) -> -40
   (28, 27) -> 40
   (28, 28) -> -40
   (29, 28) -> 40
   (29, 29) -> -40
   (30, 29) -> 40
   (30, 30) -> -40
   (31, 30) -> 40
   (31, 31) -> -40
   (32, 31) -> 40
   (32, 32) -> -40
   (33, 32) -> 40
   (33, 33) -> -40
   (34, 33) -> 40
   (34, 34) -> -40
   (35, 34) -> 40
   (35, 35) -> -40
   (36, 35) -> 40
   (36, 36) -> -40
   (37, 36) -> 40
   (37, 37) -> -30
   (38, 37) -> 30
   (38, 38) -> -40
   (39, 38) -> 40
   (39, 39) -> -60
   (40, 39) -> 60 */
  wr6 = casadi_c1;
  /* #9: @3 = mac(@4,@6,@3) */
  casadi_mtimes(w4, casadi_s3, wr6, casadi_s2, w3, casadi_s1, w, 0);
  /* #10: @7 = sparse: 40-by-39, 78 nnz
   (0, 0) -> -40
   (1, 0) -> 40
   (1, 1) -> -26.6667
   (2, 1) -> 26.6667
   (2, 2) -> -40
   (3, 2) -> 40
   (3, 3) -> -40
   (4, 3) -> 40
   (4, 4) -> -40
   (5, 4) -> 40
   (5, 5) -> -40
   (6, 5) -> 40
   (6, 6) -> -40
   (7, 6) -> 40
   (7, 7) -> -40
   (8, 7) -> 40
   (8, 8) -> -40
   (9, 8) -> 40
   (9, 9) -> -40
   (10, 9) -> 40
   (10, 10) -> -40
   (11, 10) -> 40
   (11, 11) -> -40
   (12, 11) -> 40
   (12, 12) -> -40
   (13, 12) -> 40
   (13, 13) -> -40
   (14, 13) -> 40
   (14, 14) -> -40
   (15, 14) -> 40
   (15, 15) -> -40
   (16, 15) -> 40
   (16, 16) -> -40
   (17, 16) -> 40
   (17, 17) -> -40
   (18, 17) -> 40
   (18, 18) -> -40
   (19, 18) -> 40
   (19, 19) -> -40
   (20, 19) -> 40
   (20, 20) -> -40
   (21, 20) -> 40
   (21, 21) -> -40
   (22, 21) -> 40
   (22, 22) -> -40
   (23, 22) -> 40
   (23, 23) -> -40
   (24, 23) -> 40
   (24, 24) -> -40
   (25, 24) -> 40
   (25, 25) -> -40
   (26, 25) -> 40
   (26, 26) -> -40
   (27, 26) -> 40
   (27, 27) -> -40
   (28, 27) -> 40
   (28, 28) -> -40
   (29, 28) -> 40
   (29, 29) -> -40
   (30, 29) -> 40
   (30, 30) -> -40
   (31, 30) -> 40
   (31, 31) -> -40
   (32, 31) -> 40
   (32, 32) -> -40
   (33, 32) -> 40
   (33, 33) -> -40
   (34, 33) -> 40
   (34, 34) -> -40
   (35, 34) -> 40
   (35, 35) -> -40
   (36, 35) -> 40
   (36, 36) -> -40
   (37, 36) -> 40
   (37, 37) -> -26.6667
   (38, 37) -> 26.6667
   (38, 38) -> -40
   (39, 38) -> 40 */
  wr7 = casadi_c4;
  /* #11: @2 = mac(@3,@7,@2) */
  casadi_mtimes(w3, casadi_s1, wr7, casadi_s11, w2, casadi_s10, w, 0);
  /* #12: @8 = BSplineParametric(@1, @2) */
  casadi_clear((&w8), 1);
  CASADI_PREFIX(nd_boor_eval)((&w8),1,casadi_c5,casadi_s12,casadi_s6,casadi_s6,w2,1,(&w1),casadi_s7, iw, w);
  /* #13: @9 = input[6][0] */
  w9 = arg[6] ? arg[6][0] : 0;
  /* #14: @8 = (@8*@9) */
  w8 *= w9;
  /* #15: @0 = (@0*@8) */
  w0 *= w8;
  /* #16: @8 = BSplineParametric(@1, @3) */
  casadi_clear((&w8), 1);
  CASADI_PREFIX(nd_boor_eval)((&w8),1,casadi_c2,casadi_s4,casadi_s5,casadi_s6,w3,1,(&w1),casadi_s7, iw, w);
  /* #17: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #18: @8 = (@8*@1) */
  w8 *= w1;
  /* #19: @0 = (@0+@8) */
  w0 += w8;
  /* #20: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* mpcc_heavy_cost_y_hess:(i0[13],i1[7],i2[0],i3[16],i4[],i5[213])->(o0[20x20,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a013, a053, a054, a055, a056, a057, a098, a099, a100, a101, a102, a103;
  casadi_real a104, a105, a106, a107, a108, a109, a110, a111, a112, a113, a114, a115;
  casadi_real a154, a155, a156, a195, a196, a197;
  a000=arg[3]? arg[3][0] : 0;
  a001=arg[0]? arg[0][12] : 0;
  a002=arg[5]? arg[5][6] : 0;
  a003=2.5000000000000000e-01;
  a004=(a002-a003);
  a005=(a001-a004);
  a006=arg[5]? arg[5][7] : 0;
  a007=(a005/a006);
  a008=0.;
  a009=casadi_fmax(a007,a008);
  a010=1.;
  a011=casadi_fmin(a009,a010);
  a053=(a009<=a010);
  a054=(a010<=a009);
  a054=(a053+a054);
  a053=(a053/a054);
  a054=(a008<=a007);
  a055=(a007<=a008);
  a055=(a054+a055);
  a054=(a054/a055);
  a055=(a054/a006);
  a055=(a053*a055);
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 131 : 0;
  arg[8]=0;
  arg[9]=w+42;
  arg[10]=w+43;
  res[1]=w+84;
  w[0] = a011;
  w[42] = a055;
  w[43] = a008;
  w[44] = a008;
  w[45] = a008;
  w[46] = a008;
  w[47] = a008;
  w[48] = a008;
  w[49] = a008;
  w[50] = a008;
  w[51] = a008;
  w[52] = a008;
  w[53] = a008;
  w[54] = a008;
  w[55] = a008;
  w[56] = a008;
  w[57] = a008;
  w[58] = a008;
  w[59] = a008;
  w[60] = a008;
  w[61] = a008;
  w[62] = a008;
  w[63] = a008;
  w[64] = a008;
  w[65] = a008;
  w[66] = a008;
  w[67] = a008;
  w[68] = a008;
  w[69] = a008;
  w[70] = a008;
  w[71] = a008;
  w[72] = a008;
  w[73] = a008;
  w[74] = a008;
  w[75] = a008;
  w[76] = a008;
  w[77] = a008;
  w[78] = a008;
  w[79] = a008;
  w[80] = a008;
  w[81] = a008;
  w[82] = a008;
  w[83] = a008;
  if (casadi_f1(arg+6, res+1, iw, w+85, 0)) return 1;
  a056 = w[84];
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 90 : 0;
  res[1]=w+42;
  w[0] = a011;
  if (casadi_f2(arg+6, res+1, iw, w+43, 0)) return 1;
  a098 = w[42];
  a099=casadi_sq(a098);
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 131 : 0;
  res[1]=w+42;
  w[0] = a011;
  if (casadi_f2(arg+6, res+1, iw, w+43, 0)) return 1;
  a100 = w[42];
  a101=casadi_sq(a100);
  a099=(a099+a101);
  a101=1.0000000000000001e-09;
  a099=(a099+a101);
  a099=sqrt(a099);
  a101=(a056/a099);
  a102=(a100/a099);
  a103=(a102/a099);
  a104=(a098+a098);
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 90 : 0;
  arg[8]=0;
  arg[9]=w+42;
  arg[10]=w+43;
  res[1]=w+84;
  w[0] = a011;
  w[42] = a055;
  w[43] = a008;
  w[44] = a008;
  w[45] = a008;
  w[46] = a008;
  w[47] = a008;
  w[48] = a008;
  w[49] = a008;
  w[50] = a008;
  w[51] = a008;
  w[52] = a008;
  w[53] = a008;
  w[54] = a008;
  w[55] = a008;
  w[56] = a008;
  w[57] = a008;
  w[58] = a008;
  w[59] = a008;
  w[60] = a008;
  w[61] = a008;
  w[62] = a008;
  w[63] = a008;
  w[64] = a008;
  w[65] = a008;
  w[66] = a008;
  w[67] = a008;
  w[68] = a008;
  w[69] = a008;
  w[70] = a008;
  w[71] = a008;
  w[72] = a008;
  w[73] = a008;
  w[74] = a008;
  w[75] = a008;
  w[76] = a008;
  w[77] = a008;
  w[78] = a008;
  w[79] = a008;
  w[80] = a008;
  w[81] = a008;
  w[82] = a008;
  w[83] = a008;
  if (casadi_f1(arg+6, res+1, iw, w+85, 0)) return 1;
  a105 = w[84];
  a106=(a104*a105);
  a100=(a100+a100);
  a107=(a100*a056);
  a106=(a106+a107);
  a107=(a099+a099);
  a106=(a106/a107);
  a108=(a103*a106);
  a101=(a101-a108);
  a108=(a000*a101);
  a109=arg[3]? arg[3][1] : 0;
  a110=(a105/a099);
  a098=(a098/a099);
  a111=(a098/a099);
  a112=(a111*a106);
  a110=(a110-a112);
  a112=(a109*a110);
  a108=(a108-a112);
  if (res[0]!=0) res[0][0]=a108;
  a112=(a109*a101);
  a113=(a000*a110);
  a112=(a112+a113);
  a113=(-a112);
  if (res[0]!=0) res[0][1]=a113;
  if (res[0]!=0) res[0][2]=a108;
  if (res[0]!=0) res[0][3]=a113;
  a154=arg[3]? arg[3][3] : 0;
  a154=(-a154);
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 172 : 0;
  arg[8]=0;
  arg[9]=w+42;
  arg[10]=0;
  arg[11]=0;
  arg[12]=w+43;
  arg[13]=w+44;
  arg[14]=0;
  arg[15]=w+85;
  res[1]=w+86;
  res[2]=w+87;
  w[0] = a011;
  w[42] = a154;
  w[43] = a055;
  w[44] = a008;
  w[45] = a008;
  w[46] = a008;
  w[47] = a008;
  w[48] = a008;
  w[49] = a008;
  w[50] = a008;
  w[51] = a008;
  w[52] = a008;
  w[53] = a008;
  w[54] = a008;
  w[55] = a008;
  w[56] = a008;
  w[57] = a008;
  w[58] = a008;
  w[59] = a008;
  w[60] = a008;
  w[61] = a008;
  w[62] = a008;
  w[63] = a008;
  w[64] = a008;
  w[65] = a008;
  w[66] = a008;
  w[67] = a008;
  w[68] = a008;
  w[69] = a008;
  w[70] = a008;
  w[71] = a008;
  w[72] = a008;
  w[73] = a008;
  w[74] = a008;
  w[75] = a008;
  w[76] = a008;
  w[77] = a008;
  w[78] = a008;
  w[79] = a008;
  w[80] = a008;
  w[81] = a008;
  w[82] = a008;
  w[83] = a008;
  w[84] = a008;
  w[85] = a008;
  if (casadi_f3(arg+6, res+1, iw, w+87, 0)) return 1;
  a113 = w[86];
  a155=(a102*a109);
  a156=(a098*a000);
  a155=(a155+a156);
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 49 : 0;
  arg[8]=0;
  arg[9]=w+42;
  arg[10]=0;
  arg[11]=0;
  arg[12]=w+43;
  arg[13]=w+44;
  arg[14]=0;
  arg[15]=w+85;
  res[1]=w+86;
  res[2]=w+87;
  w[0] = a011;
  w[42] = a155;
  w[43] = a055;
  w[44] = a008;
  w[45] = a008;
  w[46] = a008;
  w[47] = a008;
  w[48] = a008;
  w[49] = a008;
  w[50] = a008;
  w[51] = a008;
  w[52] = a008;
  w[53] = a008;
  w[54] = a008;
  w[55] = a008;
  w[56] = a008;
  w[57] = a008;
  w[58] = a008;
  w[59] = a008;
  w[60] = a008;
  w[61] = a008;
  w[62] = a008;
  w[63] = a008;
  w[64] = a008;
  w[65] = a008;
  w[66] = a008;
  w[67] = a008;
  w[68] = a008;
  w[69] = a008;
  w[70] = a008;
  w[71] = a008;
  w[72] = a008;
  w[73] = a008;
  w[74] = a008;
  w[75] = a008;
  w[76] = a008;
  w[77] = a008;
  w[78] = a008;
  w[79] = a008;
  w[80] = a008;
  w[81] = a008;
  w[82] = a008;
  w[83] = a008;
  w[84] = a008;
  w[85] = a112;
  if (casadi_f3(arg+6, res+1, iw, w+87, 0)) return 1;
  a155 = w[86];
  a113=(a113+a155);
  a102=(a102*a000);
  a098=(a098*a109);
  a102=(a102-a098);
  a102=(-a102);
  a108=(-a108);
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 8 : 0;
  arg[8]=0;
  arg[9]=w+42;
  arg[10]=0;
  arg[11]=0;
  arg[12]=w+43;
  arg[13]=w+44;
  arg[14]=0;
  arg[15]=w+85;
  res[1]=w+86;
  res[2]=w+87;
  w[0] = a011;
  w[42] = a102;
  w[43] = a055;
  w[44] = a008;
  w[45] = a008;
  w[46] = a008;
  w[47] = a008;
  w[48] = a008;
  w[49] = a008;
  w[50] = a008;
  w[51] = a008;
  w[52] = a008;
  w[53] = a008;
  w[54] = a008;
  w[55] = a008;
  w[56] = a008;
  w[57] = a008;
  w[58] = a008;
  w[59] = a008;
  w[60] = a008;
  w[61] = a008;
  w[62] = a008;
  w[63] = a008;
  w[64] = a008;
  w[65] = a008;
  w[66] = a008;
  w[67] = a008;
  w[68] = a008;
  w[69] = a008;
  w[70] = a008;
  w[71] = a008;
  w[72] = a008;
  w[73] = a008;
  w[74] = a008;
  w[75] = a008;
  w[76] = a008;
  w[77] = a008;
  w[78] = a008;
  w[79] = a008;
  w[80] = a008;
  w[81] = a008;
  w[82] = a008;
  w[83] = a008;
  w[84] = a008;
  w[85] = a108;
  if (casadi_f3(arg+6, res+1, iw, w+87, 0)) return 1;
  a102 = w[86];
  a113=(a113+a102);
  a102=arg[0]? arg[0][0] : 0;
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 8 : 0;
  res[1]=w+42;
  w[0] = a011;
  if (casadi_f2(arg+6, res+1, iw, w+43, 0)) return 1;
  a108 = w[42];
  a102=(a102-a108);
  a108=(a102*a109);
  a098=arg[0]? arg[0][1] : 0;
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 49 : 0;
  res[1]=w+42;
  w[0] = a011;
  if (casadi_f2(arg+6, res+1, iw, w+43, 0)) return 1;
  a195 = w[42];
  a098=(a098-a195);
  a195=(a098*a000);
  a108=(a108+a195);
  a195=(a111*a108);
  a102=(a102*a000);
  a098=(a098*a109);
  a102=(a102-a098);
  a098=(a103*a102);
  a195=(a195-a098);
  a195=(a195/a107);
  a098=(a104*a195);
  a196=(a108/a099);
  a098=(a098-a196);
  a105=(a105+a105);
  a105=(a195*a105);
  a110=(a110/a099);
  a197=(a111/a099);
  a197=(a197*a106);
  a110=(a110-a197);
  a108=(a108*a110);
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 8 : 0;
  arg[8]=0;
  arg[9]=w+42;
  arg[10]=w+43;
  res[1]=w+84;
  w[0] = a011;
  w[42] = a055;
  w[43] = a008;
  w[44] = a008;
  w[45] = a008;
  w[46] = a008;
  w[47] = a008;
  w[48] = a008;
  w[49] = a008;
  w[50] = a008;
  w[51] = a008;
  w[52] = a008;
  w[53] = a008;
  w[54] = a008;
  w[55] = a008;
  w[56] = a008;
  w[57] = a008;
  w[58] = a008;
  w[59] = a008;
  w[60] = a008;
  w[61] = a008;
  w[62] = a008;
  w[63] = a008;
  w[64] = a008;
  w[65] = a008;
  w[66] = a008;
  w[67] = a008;
  w[68] = a008;
  w[69] = a008;
  w[70] = a008;
  w[71] = a008;
  w[72] = a008;
  w[73] = a008;
  w[74] = a008;
  w[75] = a008;
  w[76] = a008;
  w[77] = a008;
  w[78] = a008;
  w[79] = a008;
  w[80] = a008;
  w[81] = a008;
  w[82] = a008;
  w[83] = a008;
  if (casadi_f1(arg+6, res+1, iw, w+85, 0)) return 1;
  a155 = w[84];
  a112=(a109*a155);
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 49 : 0;
  arg[8]=0;
  arg[9]=w+42;
  arg[10]=w+43;
  res[1]=w+84;
  w[0] = a011;
  w[42] = a055;
  w[43] = a008;
  w[44] = a008;
  w[45] = a008;
  w[46] = a008;
  w[47] = a008;
  w[48] = a008;
  w[49] = a008;
  w[50] = a008;
  w[51] = a008;
  w[52] = a008;
  w[53] = a008;
  w[54] = a008;
  w[55] = a008;
  w[56] = a008;
  w[57] = a008;
  w[58] = a008;
  w[59] = a008;
  w[60] = a008;
  w[61] = a008;
  w[62] = a008;
  w[63] = a008;
  w[64] = a008;
  w[65] = a008;
  w[66] = a008;
  w[67] = a008;
  w[68] = a008;
  w[69] = a008;
  w[70] = a008;
  w[71] = a008;
  w[72] = a008;
  w[73] = a008;
  w[74] = a008;
  w[75] = a008;
  w[76] = a008;
  w[77] = a008;
  w[78] = a008;
  w[79] = a008;
  w[80] = a008;
  w[81] = a008;
  w[82] = a008;
  w[83] = a008;
  if (casadi_f1(arg+6, res+1, iw, w+85, 0)) return 1;
  a114 = w[84];
  a115=(a000*a114);
  a112=(a112+a115);
  a111=(a111*a112);
  a108=(a108-a111);
  a101=(a101/a099);
  a111=(a103/a099);
  a111=(a111*a106);
  a101=(a101-a111);
  a101=(a102*a101);
  a109=(a109*a114);
  a155=(a000*a155);
  a109=(a109-a155);
  a103=(a103*a109);
  a101=(a101+a103);
  a108=(a108-a101);
  a108=(a108/a107);
  a107=(a195/a107);
  a101=(a106+a106);
  a107=(a107*a101);
  a108=(a108-a107);
  a104=(a104*a108);
  a105=(a105+a104);
  a112=(a112/a099);
  a196=(a196/a099);
  a196=(a196*a106);
  a112=(a112+a196);
  a105=(a105+a112);
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 90 : 0;
  arg[8]=0;
  arg[9]=w+42;
  arg[10]=0;
  arg[11]=0;
  arg[12]=w+43;
  arg[13]=w+44;
  arg[14]=0;
  arg[15]=w+85;
  res[1]=w+86;
  res[2]=w+87;
  w[0] = a011;
  w[42] = a098;
  w[43] = a055;
  w[44] = a008;
  w[45] = a008;
  w[46] = a008;
  w[47] = a008;
  w[48] = a008;
  w[49] = a008;
  w[50] = a008;
  w[51] = a008;
  w[52] = a008;
  w[53] = a008;
  w[54] = a008;
  w[55] = a008;
  w[56] = a008;
  w[57] = a008;
  w[58] = a008;
  w[59] = a008;
  w[60] = a008;
  w[61] = a008;
  w[62] = a008;
  w[63] = a008;
  w[64] = a008;
  w[65] = a008;
  w[66] = a008;
  w[67] = a008;
  w[68] = a008;
  w[69] = a008;
  w[70] = a008;
  w[71] = a008;
  w[72] = a008;
  w[73] = a008;
  w[74] = a008;
  w[75] = a008;
  w[76] = a008;
  w[77] = a008;
  w[78] = a008;
  w[79] = a008;
  w[80] = a008;
  w[81] = a008;
  w[82] = a008;
  w[83] = a008;
  w[84] = a008;
  w[85] = a105;
  if (casadi_f3(arg+6, res+1, iw, w+87, 0)) return 1;
  a057 = w[86];
  a113=(a113+a057);
  a102=(a102/a099);
  a057=(a100*a195);
  a057=(a102+a057);
  a109=(a109/a099);
  a102=(a102/a099);
  a102=(a102*a106);
  a109=(a109-a102);
  a056=(a056+a056);
  a195=(a195*a056);
  a100=(a100*a108);
  a195=(a195+a100);
  a109=(a109+a195);
  arg[6]=w+0;
  arg[7] = arg[5]? arg[5] + 131 : 0;
  arg[8]=0;
  arg[9]=w+42;
  arg[10]=0;
  arg[11]=0;
  arg[12]=w+43;
  arg[13]=w+44;
  arg[14]=0;
  arg[15]=w+85;
  res[1]=w+86;
  res[2]=w+87;
  w[0] = a011;
  w[42] = a057;
  w[43] = a055;
  w[44] = a008;
  w[45] = a008;
  w[46] = a008;
  w[47] = a008;
  w[48] = a008;
  w[49] = a008;
  w[50] = a008;
  w[51] = a008;
  w[52] = a008;
  w[53] = a008;
  w[54] = a008;
  w[55] = a008;
  w[56] = a008;
  w[57] = a008;
  w[58] = a008;
  w[59] = a008;
  w[60] = a008;
  w[61] = a008;
  w[62] = a008;
  w[63] = a008;
  w[64] = a008;
  w[65] = a008;
  w[66] = a008;
  w[67] = a008;
  w[68] = a008;
  w[69] = a008;
  w[70] = a008;
  w[71] = a008;
  w[72] = a008;
  w[73] = a008;
  w[74] = a008;
  w[75] = a008;
  w[76] = a008;
  w[77] = a008;
  w[78] = a008;
  w[79] = a008;
  w[80] = a008;
  w[81] = a008;
  w[82] = a008;
  w[83] = a008;
  w[84] = a008;
  w[85] = a109;
  if (casadi_f3(arg+6, res+1, iw, w+87, 0)) return 1;
  a013 = w[86];
  a113=(a113+a013);
  a053=(a053*a113);
  a054=(a054*a053);
  a054=(a054/a006);
  if (res[0]!=0) res[0][4]=a054;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpcc_heavy_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int mpcc_heavy_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mpcc_heavy_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_heavy_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_heavy_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_heavy_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    case 3: return casadi_s16;
    case 4: return casadi_s17;
    case 5: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_heavy_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s19;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 574;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 8*sizeof(casadi_int);
  if (sz_w) *sz_w = 574*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
