/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpcc_heavy_gripper_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {7, 1, 1};
static const casadi_int casadi_s2[3] = {213, 1, 1};

/* mpcc_heavy_gripper_expl_ode_fun:(i0[13],i1[7],i2[213])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20;
  a00=arg[0]? arg[0][5] : 0;
  a01=cos(a00);
  a02=arg[0]? arg[0][4] : 0;
  a03=cos(a02);
  a04=(a01*a03);
  a05=arg[0]? arg[0][6] : 0;
  a04=(a04*a05);
  a02=sin(a02);
  a06=(a01*a02);
  a07=arg[0]? arg[0][3] : 0;
  a08=sin(a07);
  a06=(a06*a08);
  a00=sin(a00);
  a07=cos(a07);
  a09=(a00*a07);
  a06=(a06-a09);
  a09=arg[0]? arg[0][7] : 0;
  a06=(a06*a09);
  a04=(a04+a06);
  a06=(a00*a08);
  a10=(a01*a07);
  a11=(a10*a02);
  a06=(a06+a11);
  a11=arg[0]? arg[0][8] : 0;
  a06=(a06*a11);
  a04=(a04+a06);
  if (res[0]!=0) res[0][0]=a04;
  a04=(a00*a03);
  a04=(a04*a05);
  a06=(a08*a02);
  a12=(a06*a00);
  a10=(a10+a12);
  a10=(a10*a09);
  a04=(a04+a10);
  a00=(a02*a00);
  a00=(a00*a07);
  a01=(a01*a08);
  a00=(a00-a01);
  a00=(a00*a11);
  a04=(a04+a00);
  if (res[0]!=0) res[0][1]=a04;
  a04=(a03*a08);
  a04=(a04*a09);
  a00=(a02*a05);
  a04=(a04-a00);
  a00=(a03*a07);
  a00=(a00*a11);
  a04=(a04+a00);
  if (res[0]!=0) res[0][2]=a04;
  a04=arg[0]? arg[0][9] : 0;
  a06=(a06/a03);
  a00=arg[0]? arg[0][10] : 0;
  a06=(a06*a00);
  a06=(a04+a06);
  a01=(a07*a02);
  a01=(a01/a03);
  a10=arg[0]? arg[0][11] : 0;
  a01=(a01*a10);
  a06=(a06+a01);
  if (res[0]!=0) res[0][3]=a06;
  a06=(a07*a00);
  a01=(a08*a10);
  a06=(a06-a01);
  if (res[0]!=0) res[0][4]=a06;
  a06=(a08/a03);
  a06=(a06*a00);
  a01=(a07/a03);
  a01=(a01*a10);
  a06=(a06+a01);
  if (res[0]!=0) res[0][5]=a06;
  a06=5.2018310445276737e-02;
  a01=arg[1]? arg[1][0] : 0;
  a12=arg[2]? arg[2][0] : 0;
  a01=(a01+a12);
  a12=1.3724000000000000e+01;
  a13=(a00*a11);
  a14=(a10*a09);
  a13=(a13-a14);
  a13=(a12*a13);
  a01=(a01-a13);
  a13=1.4570000000000000e+01;
  a13=(a13*a11);
  a14=(a13*a00);
  a15=1.2699999999999999e+01;
  a15=(a15*a09);
  a16=(a15*a10);
  a14=(a14-a16);
  a01=(a01-a14);
  a14=-4.0300000000000002e+00;
  a14=(a14*a05);
  a16=-1.8180000000000000e+01;
  a17=casadi_fabs(a05);
  a16=(a16*a17);
  a16=(a16*a05);
  a14=(a14+a16);
  a01=(a01+a14);
  a14=5.7098565450000081e+00;
  a14=(a14*a02);
  a01=(a01-a14);
  a06=(a06*a01);
  if (res[0]!=0) res[0][6]=a06;
  a06=3.7844383893430214e-02;
  a01=arg[1]? arg[1][1] : 0;
  a14=arg[2]? arg[2][1] : 0;
  a01=(a01+a14);
  a14=(a10*a05);
  a16=(a04*a11);
  a14=(a14-a16);
  a14=(a12*a14);
  a01=(a01-a14);
  a14=-1.4570000000000000e+01;
  a14=(a14*a11);
  a16=(a14*a04);
  a17=5.5000000000000000e+00;
  a17=(a17*a05);
  a18=(a17*a10);
  a16=(a16+a18);
  a01=(a01-a16);
  a16=-6.2199999999999998e+00;
  a16=(a16*a09);
  a18=-2.1660000000000000e+01;
  a19=casadi_fabs(a09);
  a18=(a18*a19);
  a18=(a18*a09);
  a16=(a16+a18);
  a01=(a01+a16);
  a16=-5.7098565450000081e+00;
  a16=(a16*a03);
  a18=(a16*a08);
  a01=(a01-a18);
  a06=(a06*a01);
  if (res[0]!=0) res[0][7]=a06;
  a06=3.5343182300134300e-02;
  a01=arg[1]? arg[1][2] : 0;
  a18=arg[2]? arg[2][2] : 0;
  a01=(a01+a18);
  a18=(a04*a09);
  a19=(a00*a05);
  a18=(a18-a19);
  a12=(a12*a18);
  a01=(a01-a12);
  a12=(a15*a04);
  a18=(a17*a00);
  a12=(a12-a18);
  a01=(a01-a12);
  a12=-5.1799999999999997e+00;
  a12=(a12*a11);
  a18=-3.6990000000000002e+01;
  a19=casadi_fabs(a11);
  a18=(a18*a19);
  a18=(a18*a11);
  a12=(a12+a18);
  a01=(a01+a12);
  a16=(a16*a07);
  a01=(a01-a16);
  a06=(a06*a01);
  if (res[0]!=0) res[0][8]=a06;
  a06=1.9938589145432071e+00;
  a01=arg[1]? arg[1][3] : 0;
  a16=arg[2]? arg[2][3] : 0;
  a01=(a01+a16);
  a16=-6.8260000000000098e-02;
  a16=(a16*a00);
  a16=(a16*a10);
  a01=(a01-a16);
  a13=(a13*a09);
  a16=(a15*a11);
  a13=(a13-a16);
  a16=1.2000000000000000e-01;
  a07=(a16*a10);
  a12=(a07*a00);
  a13=(a13+a12);
  a12=(a16*a00);
  a18=(a12*a10);
  a13=(a13-a18);
  a01=(a01-a13);
  a13=-7.0000000000000007e-02;
  a18=(a13*a04);
  a19=-1.5500000000000000e+00;
  a20=casadi_fabs(a04);
  a20=(a19*a20);
  a20=(a20*a04);
  a18=(a18+a20);
  a01=(a01+a18);
  a18=1.3463244000000001e+00;
  a03=(a18*a03);
  a03=(a03*a08);
  a01=(a01-a03);
  a06=(a06*a01);
  if (res[0]!=0) res[0][9]=a06;
  a06=1.1138338159946535e+00;
  a01=arg[1]? arg[1][4] : 0;
  a03=arg[2]? arg[2][4] : 0;
  a01=(a01+a03);
  a03=-3.2799999999999996e-01;
  a03=(a03*a04);
  a03=(a03*a10);
  a01=(a01-a03);
  a14=(a14*a05);
  a11=(a17*a11);
  a14=(a14+a11);
  a07=(a07*a04);
  a14=(a14-a07);
  a16=(a16*a04);
  a07=(a16*a10);
  a14=(a14+a07);
  a01=(a01-a14);
  a14=(a13*a00);
  a07=casadi_fabs(a00);
  a07=(a19*a07);
  a07=(a07*a00);
  a14=(a14+a07);
  a01=(a01+a14);
  a18=(a18*a02);
  a01=(a01-a18);
  a06=(a06*a01);
  if (res[0]!=0) res[0][10]=a06;
  a06=1.2054873785471467e+00;
  a01=arg[1]? arg[1][5] : 0;
  a18=arg[2]? arg[2][5] : 0;
  a01=(a01+a18);
  a18=3.9626000000000006e-01;
  a18=(a18*a04);
  a18=(a18*a00);
  a01=(a01-a18);
  a15=(a15*a05);
  a17=(a17*a09);
  a15=(a15-a17);
  a12=(a12*a04);
  a15=(a15+a12);
  a16=(a16*a00);
  a15=(a15-a16);
  a01=(a01-a15);
  a13=(a13*a10);
  a15=casadi_fabs(a10);
  a19=(a19*a15);
  a19=(a19*a10);
  a13=(a13+a19);
  a01=(a01+a13);
  a06=(a06*a01);
  if (res[0]!=0) res[0][11]=a06;
  a06=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][12]=a06;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpcc_heavy_gripper_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int mpcc_heavy_gripper_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mpcc_heavy_gripper_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_heavy_gripper_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_heavy_gripper_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_heavy_gripper_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_heavy_gripper_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
