/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpcc_heavy_gripper_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {7, 1, 1};
static const casadi_int casadi_s2[3] = {213, 1, 1};
static const casadi_int casadi_s3[3] = {20, 1, 1};

/* mpcc_heavy_gripper_expl_vde_adj:(i0[13],i1[13],i2[7],i3[213])->(o0[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a01=arg[0]? arg[0][3] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][10] : 0;
  a04=arg[1]? arg[1][5] : 0;
  a05=(a03*a04);
  a06=arg[0]? arg[0][4] : 0;
  a07=cos(a06);
  a08=(a05/a07);
  a09=1.3463244000000001e+00;
  a10=(a09*a07);
  a11=1.9938589145432071e+00;
  a12=arg[1]? arg[1][9] : 0;
  a11=(a11*a12);
  a10=(a10*a11);
  a12=-5.7098565450000081e+00;
  a13=(a12*a07);
  a14=3.7844383893430214e-02;
  a15=arg[1]? arg[1][7] : 0;
  a14=(a14*a15);
  a15=(a13*a14);
  a10=(a10+a15);
  a08=(a08-a10);
  a10=arg[0]? arg[0][11] : 0;
  a15=arg[1]? arg[1][4] : 0;
  a16=(a10*a15);
  a08=(a08-a16);
  a06=sin(a06);
  a16=arg[1]? arg[1][3] : 0;
  a17=(a03*a16);
  a18=(a17/a07);
  a19=(a06*a18);
  a08=(a08+a19);
  a19=arg[0]? arg[0][7] : 0;
  a20=arg[1]? arg[1][2] : 0;
  a21=(a19*a20);
  a22=(a07*a21);
  a08=(a08+a22);
  a22=arg[0]? arg[0][5] : 0;
  a23=cos(a22);
  a24=arg[0]? arg[0][8] : 0;
  a25=arg[1]? arg[1][1] : 0;
  a26=(a24*a25);
  a27=(a23*a26);
  a08=(a08-a27);
  a22=sin(a22);
  a27=(a19*a25);
  a28=(a22*a27);
  a29=(a06*a28);
  a08=(a08+a29);
  a29=arg[1]? arg[1][0] : 0;
  a30=(a24*a29);
  a31=(a22*a30);
  a08=(a08+a31);
  a31=(a23*a06);
  a32=(a19*a29);
  a33=(a31*a32);
  a08=(a08+a33);
  a08=(a02*a08);
  a01=sin(a01);
  a33=(a10*a04);
  a34=(a33/a07);
  a35=3.5343182300134300e-02;
  a36=arg[1]? arg[1][8] : 0;
  a35=(a35*a36);
  a13=(a13*a35);
  a34=(a34-a13);
  a13=(a03*a15);
  a34=(a34+a13);
  a13=(a10*a16);
  a36=(a13/a07);
  a37=(a06*a36);
  a34=(a34+a37);
  a37=(a24*a20);
  a38=(a07*a37);
  a34=(a34+a38);
  a38=(a06*a22);
  a39=(a38*a26);
  a34=(a34+a39);
  a39=(a23*a27);
  a34=(a34+a39);
  a39=(a06*a30);
  a40=(a23*a39);
  a34=(a34+a40);
  a40=(a22*a32);
  a34=(a34-a40);
  a34=(a01*a34);
  a08=(a08-a34);
  if (res[0]!=0) res[0][3]=a08;
  a36=(a02*a36);
  a08=1.1138338159946535e+00;
  a34=arg[1]? arg[1][10] : 0;
  a08=(a08*a34);
  a34=(a09*a08);
  a40=5.7098565450000081e+00;
  a41=5.2018310445276737e-02;
  a42=arg[1]? arg[1][6] : 0;
  a41=(a41*a42);
  a40=(a40*a41);
  a34=(a34+a40);
  a36=(a36-a34);
  a18=(a01*a18);
  a36=(a36+a18);
  a18=arg[0]? arg[0][6] : 0;
  a34=(a18*a20);
  a36=(a36-a34);
  a34=(a02*a26);
  a40=(a22*a34);
  a36=(a36+a40);
  a28=(a01*a28);
  a36=(a36+a28);
  a28=(a23*a02);
  a40=(a28*a30);
  a36=(a36+a40);
  a40=(a01*a32);
  a42=(a23*a40);
  a36=(a36+a42);
  a36=(a07*a36);
  a37=(a02*a37);
  a42=(a01*a11);
  a09=(a09*a42);
  a42=(a02*a35);
  a42=(a12*a42);
  a09=(a09+a42);
  a42=(a01*a14);
  a12=(a12*a42);
  a09=(a09+a12);
  a12=(a02/a07);
  a42=(a12/a07);
  a42=(a42*a33);
  a09=(a09+a42);
  a42=(a01/a07);
  a33=(a42/a07);
  a33=(a33*a05);
  a09=(a09+a33);
  a33=(a02*a06);
  a33=(a33/a07);
  a05=(a33/a07);
  a05=(a05*a13);
  a09=(a09+a05);
  a05=(a01*a06);
  a13=(a05/a07);
  a43=(a13/a07);
  a43=(a43*a17);
  a09=(a09+a43);
  a37=(a37-a09);
  a21=(a01*a21);
  a37=(a37+a21);
  a21=(a18*a25);
  a09=(a22*a21);
  a37=(a37+a09);
  a09=(a18*a29);
  a43=(a23*a09);
  a37=(a37+a43);
  a37=(a06*a37);
  a36=(a36-a37);
  if (res[0]!=0) res[0][4]=a36;
  a34=(a06*a34);
  a36=(a05*a27);
  a34=(a34+a36);
  a21=(a07*a21);
  a34=(a34+a21);
  a30=(a01*a30);
  a34=(a34+a30);
  a32=(a02*a32);
  a34=(a34-a32);
  a34=(a23*a34);
  a27=(a02*a27);
  a26=(a01*a26);
  a27=(a27-a26);
  a39=(a02*a39);
  a27=(a27+a39);
  a40=(a06*a40);
  a27=(a27+a40);
  a09=(a07*a09);
  a27=(a27+a09);
  a27=(a22*a27);
  a34=(a34-a27);
  if (res[0]!=0) res[0][5]=a34;
  a34=5.5000000000000000e+00;
  a27=1.2054873785471467e+00;
  a09=arg[1]? arg[1][11] : 0;
  a27=(a27*a09);
  a09=(a19*a27);
  a09=(a34*a09);
  a40=1.2699999999999999e+01;
  a39=(a40*a19);
  a26=(a39*a27);
  a09=(a09-a26);
  a26=(a24*a08);
  a26=(a34*a26);
  a09=(a09-a26);
  a26=-1.4570000000000000e+01;
  a32=(a26*a24);
  a30=(a32*a08);
  a09=(a09-a30);
  a30=(a03*a35);
  a30=(a34*a30);
  a09=(a09+a30);
  a30=1.3724000000000000e+01;
  a21=(a30*a35);
  a36=(a03*a21);
  a09=(a09+a36);
  a36=(a10*a14);
  a36=(a34*a36);
  a09=(a09-a36);
  a36=(a30*a14);
  a37=(a10*a36);
  a09=(a09-a37);
  a37=-1.8180000000000000e+01;
  a43=casadi_fabs(a18);
  a43=(a37*a43);
  a43=(a43*a41);
  a09=(a09+a43);
  a43=casadi_sign(a18);
  a17=(a18*a41);
  a37=(a37*a17);
  a43=(a43*a37);
  a09=(a09+a43);
  a43=-4.0300000000000002e+00;
  a43=(a43*a41);
  a09=(a09+a43);
  a43=(a06*a20);
  a09=(a09-a43);
  a43=(a22*a07);
  a43=(a43*a25);
  a09=(a09+a43);
  a43=(a23*a07);
  a43=(a43*a29);
  a09=(a09+a43);
  if (res[0]!=0) res[0][6]=a09;
  a34=(a34*a18);
  a09=(a34*a27);
  a43=(a18*a27);
  a43=(a40*a43);
  a09=(a09-a43);
  a43=(a24*a11);
  a43=(a40*a43);
  a09=(a09+a43);
  a43=1.4570000000000000e+01;
  a37=(a43*a24);
  a17=(a37*a11);
  a09=(a09-a17);
  a17=arg[0]? arg[0][9] : 0;
  a44=(a17*a35);
  a44=(a40*a44);
  a09=(a09-a44);
  a44=(a17*a21);
  a09=(a09-a44);
  a44=-2.1660000000000000e+01;
  a45=casadi_fabs(a19);
  a45=(a44*a45);
  a45=(a45*a14);
  a09=(a09+a45);
  a45=casadi_sign(a19);
  a46=(a19*a14);
  a44=(a44*a46);
  a45=(a45*a44);
  a09=(a09+a45);
  a45=-6.2199999999999998e+00;
  a45=(a45*a14);
  a09=(a09+a45);
  a45=(a10*a41);
  a40=(a40*a45);
  a09=(a09+a40);
  a30=(a30*a41);
  a40=(a10*a30);
  a09=(a09+a40);
  a40=(a07*a01);
  a40=(a40*a20);
  a09=(a09+a40);
  a05=(a05*a22);
  a05=(a28+a05);
  a05=(a05*a25);
  a09=(a09+a05);
  a31=(a31*a01);
  a05=(a22*a02);
  a31=(a31-a05);
  a31=(a31*a29);
  a09=(a09+a31);
  if (res[0]!=0) res[0][7]=a09;
  a09=(a39*a11);
  a31=(a34*a08);
  a05=(a18*a08);
  a05=(a26*a05);
  a31=(a31+a05);
  a09=(a09-a31);
  a31=(a19*a11);
  a31=(a43*a31);
  a09=(a09-a31);
  a31=-3.6990000000000002e+01;
  a05=casadi_fabs(a24);
  a05=(a31*a05);
  a05=(a05*a35);
  a09=(a09+a05);
  a05=casadi_sign(a24);
  a40=(a24*a35);
  a31=(a31*a40);
  a05=(a05*a31);
  a09=(a09+a05);
  a05=-5.1799999999999997e+00;
  a05=(a05*a35);
  a09=(a09+a05);
  a05=(a17*a14);
  a26=(a26*a05);
  a09=(a09-a26);
  a26=(a17*a36);
  a09=(a09+a26);
  a26=(a03*a41);
  a43=(a43*a26);
  a09=(a09-a43);
  a43=(a03*a30);
  a09=(a09-a43);
  a07=(a07*a02);
  a07=(a07*a20);
  a09=(a09+a07);
  a38=(a38*a02);
  a23=(a23*a01);
  a38=(a38-a23);
  a38=(a38*a25);
  a09=(a09+a38);
  a22=(a22*a01);
  a28=(a28*a06);
  a22=(a22+a28);
  a22=(a22*a29);
  a09=(a09+a22);
  if (res[0]!=0) res[0][8]=a09;
  a09=1.2000000000000000e-01;
  a22=(a03*a27);
  a29=(a09*a22);
  a28=(a09*a03);
  a06=(a28*a27);
  a29=(a29-a06);
  a06=3.9626000000000006e-01;
  a22=(a06*a22);
  a29=(a29-a22);
  a22=(a10*a08);
  a38=(a09*a22);
  a29=(a29-a38);
  a38=(a09*a10);
  a25=(a38*a08);
  a29=(a29+a25);
  a25=-3.2799999999999996e-01;
  a22=(a25*a22);
  a29=(a29-a22);
  a22=-1.5500000000000000e+00;
  a23=casadi_fabs(a17);
  a23=(a22*a23);
  a23=(a23*a11);
  a29=(a29+a23);
  a23=casadi_sign(a17);
  a07=(a17*a11);
  a07=(a22*a07);
  a23=(a23*a07);
  a29=(a29+a23);
  a23=-7.0000000000000007e-02;
  a07=(a23*a11);
  a29=(a29+a07);
  a07=(a39*a35);
  a29=(a29-a07);
  a07=(a19*a21);
  a29=(a29-a07);
  a32=(a32*a14);
  a29=(a29-a32);
  a32=(a24*a36);
  a29=(a29+a32);
  a29=(a29+a16);
  if (res[0]!=0) res[0][9]=a29;
  a29=(a09*a17);
  a32=(a29*a27);
  a07=(a17*a27);
  a07=(a09*a07);
  a32=(a32-a07);
  a06=(a06*a17);
  a06=(a06*a27);
  a32=(a32-a06);
  a06=casadi_fabs(a03);
  a06=(a22*a06);
  a06=(a06*a08);
  a32=(a32+a06);
  a06=casadi_sign(a03);
  a07=(a03*a08);
  a07=(a22*a07);
  a06=(a06*a07);
  a32=(a32+a06);
  a06=(a23*a08);
  a32=(a32+a06);
  a06=(a10*a11);
  a07=(a09*a06);
  a32=(a32+a07);
  a38=(a38*a11);
  a32=(a32-a38);
  a38=-6.8260000000000098e-02;
  a06=(a38*a06);
  a32=(a32-a06);
  a06=(a34*a35);
  a32=(a32+a06);
  a21=(a18*a21);
  a32=(a32+a21);
  a37=(a37*a41);
  a32=(a32-a37);
  a24=(a24*a30);
  a32=(a32-a24);
  a42=(a42*a04);
  a32=(a32+a42);
  a02=(a02*a15);
  a32=(a32+a02);
  a13=(a13*a16);
  a32=(a32+a13);
  if (res[0]!=0) res[0][10]=a32;
  a32=casadi_fabs(a10);
  a32=(a22*a32);
  a32=(a32*a27);
  a13=casadi_sign(a10);
  a10=(a10*a27);
  a22=(a22*a10);
  a13=(a13*a22);
  a32=(a32+a13);
  a23=(a23*a27);
  a32=(a32+a23);
  a29=(a29*a08);
  a32=(a32-a29);
  a29=(a17*a08);
  a29=(a09*a29);
  a32=(a32+a29);
  a25=(a25*a17);
  a25=(a25*a08);
  a32=(a32-a25);
  a28=(a28*a11);
  a32=(a32+a28);
  a28=(a03*a11);
  a09=(a09*a28);
  a32=(a32-a09);
  a38=(a38*a03);
  a38=(a38*a11);
  a32=(a32-a38);
  a34=(a34*a14);
  a32=(a32-a34);
  a18=(a18*a36);
  a32=(a32-a18);
  a39=(a39*a41);
  a32=(a32+a39);
  a19=(a19*a30);
  a32=(a32+a19);
  a12=(a12*a04);
  a32=(a32+a12);
  a01=(a01*a15);
  a32=(a32-a01);
  a33=(a33*a16);
  a32=(a32+a33);
  if (res[0]!=0) res[0][11]=a32;
  if (res[0]!=0) res[0][12]=a00;
  if (res[0]!=0) res[0][13]=a41;
  if (res[0]!=0) res[0][14]=a14;
  if (res[0]!=0) res[0][15]=a35;
  if (res[0]!=0) res[0][16]=a11;
  if (res[0]!=0) res[0][17]=a08;
  if (res[0]!=0) res[0][18]=a27;
  a27=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][19]=a27;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpcc_heavy_gripper_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mpcc_heavy_gripper_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mpcc_heavy_gripper_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_heavy_gripper_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_heavy_gripper_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_heavy_gripper_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_heavy_gripper_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
