#!/usr/bin/env python3
"""Generate bluerov_heavy_c3.xml from bluerov_heavy.xml (C3-only payload variant).

heavy_c3 = BlueROV2 Heavy + MarineSitu C3 stereo camera on its C3-BR bracket, rigidly
bolted. This is EXACTLY what the lab's Onshape assembly contains — the Newton gripper is
NOT in Onshape yet, so it is deliberately absent here (add it via tools/gen_gripper_variant.py's
heavy_gripper variant once it exists in CAD). Sibling of tools/gen_gripper_variant.py; same
philosophy (string surgery on unique anchors, composed numbers, never hand-edit the output).

THE BODY FRAME IS RE-ORIGINED AT THE COMPOSITE (C3-shifted) COM. The whole stack — the
dobmpc Fossen predictor, params.ZG_MASS=0, hydro's force application — assumes body
origin == COM (true for heavy by construction). So every positioned element inherited from
heavy (thruster sites, collision box, skin meshes, base_origin marker) is shifted by
-COM, and the C3 payload is placed in the same shifted frame. With no articulated bodies
the composite COM IS the whole-vehicle COM (compute_payload_inertia.compose_c3()).

C3 placement + orientation come from the lab's Onshape assembly (2026-07-19; onshape-to-robot
export + mesh registration — see tools/process_c3_mesh.py). The C3 sits front-bottom on the
centreline, lens forward and level; the 3 cameras sit at the lens plane. Numbers are read
from meshes/c3_payload_frames.json (drift-guarded against CP.C3_POS).

Run in `robust`:  python tools/gen_c3_variant.py
"""
import json
import os
import sys
import re

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # package root
import compute_payload_inertia as CP

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "bluerov_heavy.xml")
DST = os.path.join(HERE, "bluerov_heavy_c3.xml")

STEREO_HALF_BASE = 0.0375     # C3 stereo baseline 7.5 cm


def _sub_once(text, pattern, repl, what):
    new, n = re.subn(pattern, repl, text, count=1, flags=re.DOTALL)
    if n != 1:
        raise RuntimeError(f"anchor not found (exactly once) for: {what}")
    return new


def _quat_to_R(q):
    w, x, y, z = q
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - w * z), 2 * (x * z + w * y)],
        [2 * (x * y + w * z), 1 - 2 * (x * x + z * z), 2 * (y * z - w * x)],
        [2 * (x * z - w * y), 2 * (y * z + w * x), 1 - 2 * (x * x + y * y)],
    ])


def _verify_mesh_geoms(xml_path, expect):
    """Compile the emitted XML and check each payload mesh actually RENDERS at its
    intended pose: MuJoCo re-orients every mesh to principal axes internally but
    COMPOSES that reframe into the compiled geom pos/quat, so a geom's XML pos/quat
    apply directly to the AUTHORED mesh (geom quat identity == render as baked; this
    is also why the quat-less rovc_* skins render correctly). This guard reconstructs
    the rendered vertices from the compiled model and asserts their bbox matches the
    baked STL placed at the intended position (catches any regression in that chain —
    a wrong 'cancellation' quat shipped twice before this existed)."""
    import mujoco
    m = mujoco.MjModel.from_xml_path(xml_path)
    for mesh_name, (want_pos, stl) in expect.items():
        mid = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_MESH, mesh_name)
        v = m.mesh_vert[m.mesh_vertadr[mid]:m.mesh_vertadr[mid] + m.mesh_vertnum[mid]]
        gi = next(g for g in range(m.ngeom) if m.geom_dataid[g] == mid)
        rendered = v.astype(float) @ _quat_to_R(m.geom_quat[gi]).T + m.geom_pos[gi]
        import trimesh
        ref = trimesh.load(os.path.join(HERE, "meshes", stl), force="mesh", process=False)
        want = np.asarray(ref.vertices) + np.asarray(want_pos)
        if not (np.allclose(rendered.min(0), want.min(0), atol=1e-3)
                and np.allclose(rendered.max(0), want.max(0), atol=1e-3)):
            raise RuntimeError(
                f"{mesh_name}: rendered bbox {rendered.min(0)}..{rendered.max(0)} != "
                f"intended {want.min(0)}..{want.max(0)} — mesh orientation regression")
    print(f"  [verify] payload meshes render at their intended pose ({len(expect)} checked)")


def _fmt(v):
    return " ".join(f"{x:.5f}" for x in v)


def build():
    M, com, I, _ = CP.compose_c3()      # no articulated bodies -> com is the total COM
    src = open(SRC).read()

    header = (
        "<!-- GENERATED by tools/gen_c3_variant.py from bluerov_heavy.xml - DO NOT EDIT BY HAND "
        "(rerun the script).\n"
        "     BlueROV2 Heavy + MarineSitu C3 stereo camera on its C3-BR bracket = exactly "
        "the lab's Onshape assembly\n"
        "     (NO Newton gripper - not in Onshape yet). BODY FRAME RE-ORIGINED at the "
        f"composite COM (shift {_fmt(com)}\n"
        "     from the heavy frame) so origin==COM, which the dobmpc predictor / "
        "params.ZG_MASS=0 / hydro all assume.\n"
        "     C3 baked into <inertial> (bracket is visual-only, mass unknown). Hydro coeffs "
        "stay the heavy set except\n"
        "     volume/coBM (marinegym_assets/BlueROVHeavyC3.yaml). Net buoyancy ~-3.1 N "
        "(C3 payload, no trim foam - SINKS).\n"
        "     C3 pose measured from Onshape 2026-07-19 (tools/process_c3_mesh.py). See "
        "compute_payload_inertia.py. -->\n")

    out = _sub_once(src, r'<mujoco model="[^"]*">',
                    '<mujoco model="bluerov2_heavy_c3">\n' + header, "model name")

    # 1. composite inertial: origin == COM, so pos = 0. DIAGONAL on purpose (a fullinertia
    # gets axis-permuted by MuJoCo's principal-axis sort, breaking hydro's body-frame drag
    # - see tools/gen_gripper_variant.py / KNOWN_ISSUES). Dropped Ixz = +0.046 (12.4% of Ixx) is
    # a real roll-yaw product the plant can't carry until hydro reads body-frame velocity.
    di = f"{I[0,0]:.5f} {I[1,1]:.5f} {I[2,2]:.5f}"
    out = _sub_once(
        out, r'<inertial pos="0 0 0" mass="11\.5" diaginertia="[^"]*"/>',
        f'<inertial pos="0 0 0" mass="{M:.4f}" diaginertia="{di}"/>\n'
        f'      <!-- ^ composite: heavy 11.5 + C3 1.700 kg; frame origin = composite COM. '
        f'DIAGONAL inertia so body_iquat\n'
        f'           stays identity (fullinertia would axis-permute the inertial frame and '
        f'break hydro drag). -->',
        "heavy inertial")

    # 2a. shift the 8 thruster sites by -com (relative-to-COM positions preserved)
    def shift_site(match):
        name, x, y, z, rest = match.groups()
        p = np.array([float(x), float(y), float(z)]) - com
        return f'<site name="{name}" class="thruster" pos="{_fmt(p)}"{rest}'
    out, n = re.subn(
        r'<site name="(thruster_\d)" class="thruster" pos="([\-\d.e]+) ([\-\d.e]+) ([\-\d.e]+)"([^/]*/>)',
        shift_site, out)
    if n != 8:
        raise RuntimeError(f"expected 8 thruster sites, patched {n}")

    # 2b. collision box
    def shift_geom(match):
        x, y, z, rest = match.groups()
        p = np.array([float(x), float(y), float(z)]) - com
        return f'<geom class="collision" pos="{_fmt(p)}"{rest}'
    out, n = re.subn(
        r'<geom class="collision" pos="([\-\d.e]+) ([\-\d.e]+) ([\-\d.e]+)"([^/]*/>)',
        shift_geom, out)
    if n != 1:
        raise RuntimeError("collision box not patched")

    # 2c. colored-skin meshes (verts are in the OLD heavy frame -> offset by -com)
    out, n = re.subn(r'(<geom class="visual"\s+mesh="rovc_\w+"\s+material="rovc_\w+")\s*/>',
                     rf'\1 pos="{_fmt(-com)}"/>', out)
    if n != 4:
        raise RuntimeError(f"expected 4 skin geoms, patched {n}")

    # 2d. base_origin marker: keep marking the OLD geometric origin
    out = _sub_once(out, r'<site name="base_origin" class="ref" pos="0 0 0"',
                    f'<site name="base_origin" class="ref" pos="{_fmt(-com)}"',
                    "base_origin site")

    # 3. C3 payload subtree (positions in the NEW frame), before the base_origin comment.
    # C3/bracket/camera placement from the Onshape-derived meta; guard against CP drift.
    meta = json.load(open(os.path.join(HERE, "meshes", "c3_payload_frames.json")))
    if np.linalg.norm(np.array(meta["c3_centroid_bl"]) - CP.C3_POS) > 1e-3:
        raise RuntimeError("CP.C3_POS disagrees with meshes/c3_payload_frames.json — "
                           "rerun tools/process_c3_mesh.py and update compute_payload_inertia.py")
    c3 = CP.C3_POS - com
    mt = np.array(meta["mount_centroid_bl"]) - com
    cam = np.array(meta["cam_center_bl"]) - com
    cam_xy = " ".join(f"{v:.5f}" for v in meta["cam_xyaxes"])
    payload = f"""
      <!-- ===== PAYLOAD: MarineSitu C3 stereo camera + C3-BR bracket (real CAD meshes,
           FRONT-BOTTOM, lens FORWARD level — measured from the Onshape assembly
           2026-07-19, meshes/c3_payload_frames.json). The STLs are pre-baked into the
           mount orientation, so the geoms need NO quat: MuJoCo composes its internal
           principal-axis reframe back into the compiled geom pose, i.e. geom pos/quat
           apply to the mesh AS AUTHORED (same reason the quat-less rovc_* skins render
           correctly). The 3 <camera>s sit at the LENS PLANE (xyaxes). ===== -->
      <geom class="visual" type="mesh" mesh="c3_mount" pos="{_fmt(mt)}"
            material="c3_mount_gray"/>
      <geom class="visual" type="mesh" mesh="c3_camera" pos="{_fmt(c3)}"
            material="c3_housing"/>
      <camera name="c3_center" pos="{cam[0]:.5f} {cam[1]:.5f} {cam[2]:.5f}"
              xyaxes="{cam_xy}" fovy="52.5"/>
      <camera name="c3_left" pos="{cam[0]:.5f} {cam[1] + STEREO_HALF_BASE:.5f} {cam[2]:.5f}"
              xyaxes="{cam_xy}" fovy="55.5"/>
      <camera name="c3_right" pos="{cam[0]:.5f} {cam[1] - STEREO_HALF_BASE:.5f} {cam[2]:.5f}"
              xyaxes="{cam_xy}" fovy="55.5"/>
"""
    out = _sub_once(out, r'(\n\s*<!-- reference site at the base_link origin -->)',
                    payload + r"\1", "payload subtree insert")

    # C3 housing + bracket materials (EXACT Onshape appearance rgba, from the export's
    # robot.xml materials: housing blue 0.231/0.380/0.706, bracket gray 0.753) + meshes
    out = _sub_once(out, r'(<material name="collision"[^/]*/>)',
                    r'\1' + '\n    <material name="c3_housing" '
                    'rgba="0.231373 0.380392 0.705882 1" specular="0.35" shininess="0.4"/>'
                    '\n    <material name="c3_mount_gray" rgba="0.752941 0.752941 0.752941 1" '
                    'specular="0.4" shininess="0.4"/>'
                    '\n    <mesh name="c3_camera" file="c3_camera.stl" inertia="shell"/>'
                    '\n    <mesh name="c3_mount" file="c3_mount.stl" inertia="shell"/>',
                    "c3 material + mesh")

    with open(DST, "w") as f:
        f.write(out)
    _verify_mesh_geoms(DST, {"c3_camera": (c3, "c3_camera.stl"),
                             "c3_mount": (mt, "c3_mount.stl")})
    print(f"wrote {os.path.basename(DST)}: origin=COM {_fmt(com)}, mass {M:.4f} kg, "
          f"I diag [{di}]")


if __name__ == "__main__":
    build()
