/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpcc_heavy_gripper_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_low CASADI_PREFIX(low)
#define casadi_lsqr_single_solve CASADI_PREFIX(lsqr_single_solve)
#define casadi_lsqr_solve CASADI_PREFIX(lsqr_solve)
#define casadi_lsqr_sym_ortho CASADI_PREFIX(lsqr_sym_ortho)
#define casadi_mv CASADI_PREFIX(mv)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_mv(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, casadi_real* z, casadi_int tr) {
  casadi_int ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!x || !y || !z) return;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el<colind_x[i+1]; ++el) {
        z[i] += x[el] * y[row_x[el]];
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el<colind_x[i+1]; ++el) {
        z[row_x[el]] += x[el] * y[i];
      }
    }
  }
}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

void casadi_lsqr_sym_ortho(casadi_real a, casadi_real b, casadi_real* cs, casadi_real* sn, casadi_real* rho) {
    casadi_real tau;
    if (b == 0) {
        *cs = casadi_sign(a);
        *sn = 0;
        *rho = casadi_fabs(a);
    } else if (a==0) {
        *cs = 0;
        *sn = casadi_sign(b);
        *rho = casadi_fabs(b);
    } else if (casadi_fabs(b)>casadi_fabs(a)) {
        tau = a/b;
        *sn = casadi_sign(b)/sqrt(1+tau*tau);
        *cs = (*sn)*tau;
        *rho = b/(*sn);
    } else {
        tau = b/a;
        *cs = casadi_sign(a)/sqrt(1+tau*tau);
        *sn = (*cs)*tau;
        *rho = a/(*cs);
    }
}
int casadi_lsqr_single_solve(const casadi_real* A, casadi_real* x, casadi_int tr, const casadi_int* sp, casadi_real* w) {
    casadi_int m, n, i;
    casadi_real damp, atol, btol, conlim, ctol, anorm, acond, dampsq, ddnorm, res2, xnorm, xxnorm, z;
    casadi_real cs2, sn2, alpha, beta, rhobar, phibar, bnorm, rnorm, arnorm, rhobar1, cs1, sn1, psi;
    casadi_real cs, sn, rho, theta, phi, tau, t1, t2, n2dk, delta, gambar, rhs, zbar, gamma, res1;
    casadi_real r1sq, r1norm, test1, test2, test3, rtol;
    casadi_int iter_lim, itn, istop;
    casadi_real *u, *v, *xx, *ww, *dk;
    m = sp[0];
    n = sp[1];
    damp = 0;
    atol = 1e-15;
    btol = 1e-15;
    conlim = 1e8;
    iter_lim = 10000;
    itn = 0;
    istop = 0;
    ctol = 0;
    if (conlim > 0) ctol = 1/conlim;
    anorm = 0;
    acond = 0;
    dampsq = damp*damp;
    ddnorm = 0;
    res2 = 0;
    xnorm = 0;
    xxnorm = 0;
    z = 0;
    cs2 = -1;
    sn2 = 0;
    u = w;  w+= m; casadi_copy(x, m, u);
    v = w;  w+= n; casadi_clear(v, n);
    xx = w; w+= n; casadi_clear(xx, n);
    ww = w; w+= n; casadi_clear(v, n);
    dk = w; w+= n;
    alpha = 0;
    beta = casadi_norm_2(m, u);
    if (beta>0) {
      for (i=0;i<m;++i) u[i]*=1/beta;
      casadi_mv(A, sp, u, v, !tr);
      alpha = casadi_norm_2(n, v);
    }
    if (alpha>0) {
      for (i=0;i<n;++i) v[i]*=1/alpha;
      casadi_copy(v, n, ww);
    }
    rhobar = alpha;
    phibar = beta;
    bnorm = beta;
    rnorm = beta;
    arnorm = alpha * beta;
    if (arnorm==0.0) {
      casadi_clear(x, m);
      return 0;
    }
    while (itn<iter_lim) {
      itn++;
      for (i=0;i<m;++i) u[i]*=-alpha;
      casadi_mv(A, sp, v, u, tr);
      beta = casadi_norm_2(m, u);
      if (beta>0) {
        for (i=0;i<m;++i) u[i]*=1/beta;
        anorm = sqrt(anorm*anorm + alpha*alpha+beta*beta+damp*damp);
        for (i=0;i<n;++i) v[i]*=-beta;
        casadi_mv(A, sp, u, v, !tr);
        alpha = casadi_norm_2(n, v);
        if (alpha>0) for (i=0;i<n;++i) v[i]*=1/alpha;
      }
      rhobar1 = sqrt(rhobar*rhobar+damp*damp);
      cs1 = rhobar / rhobar1;
      sn1 = damp / rhobar1;
      psi = sn1 * phibar;
      phibar *= cs1;
      casadi_lsqr_sym_ortho(rhobar1, beta, &cs, &sn, &rho);
      theta = sn * alpha;
      rhobar = -cs * alpha;
      phi = cs * phibar;
      phibar *= sn;
      tau = sn * phi;
      t1 = phi / rho;
      t2 = -theta / rho;
      for (i=0;i<n;++i) dk[i]=ww[i]/rho;
      for (i=0; i<n; ++i) xx[i] += t1*ww[i];
      for (i=0; i<n; ++i) ww[i] = v[i] + t2*ww[i];
      n2dk = casadi_norm_2(n, dk);
      ddnorm += n2dk*n2dk;
      delta = sn2 * rho;
      gambar = -cs2 * rho;
      rhs = phi - delta * z;
      zbar = rhs / gambar;
      xnorm = sqrt(xxnorm + zbar*zbar);
      gamma = sqrt(gambar*gambar + theta*theta);
      cs2 = gambar / gamma;
      sn2 = theta / gamma;
      z = rhs / gamma;
      xxnorm += z*z;
      acond = anorm * sqrt(ddnorm);
      res1 = phibar*phibar;
      res2 += psi*psi;
      rnorm = sqrt(res1+res2);
      arnorm = alpha*casadi_fabs(tau);
      r1sq = rnorm*rnorm - dampsq * xxnorm;
      r1norm = sqrt(casadi_fabs(r1sq));
      if (r1sq < 0) r1norm = -r1norm;
      test1 = rnorm / bnorm;
      test2 = arnorm / (anorm * rnorm);
      test3 = 1 / acond;
      t1 = test1 / (1 + anorm * xnorm / bnorm);
      rtol = btol + atol * anorm * xnorm / bnorm;
      if (itn >= iter_lim) istop = 7;
      if (1 + test3 <= 1) istop = 6;
      if (1 + test2 <= 1) istop = 5;
      if (1 + t1 <= 1) istop = 4;
      if (test3 <= ctol) istop = 3;
      if (test2 <= atol) istop = 2;
      if (test1 <= rtol) istop = 1;
      if (istop != 0) break;
    }
    casadi_copy(xx, m, x);
    return 0;
}
int casadi_lsqr_solve(const casadi_real* A, casadi_real* x, casadi_int nrhs, casadi_int tr,
        const casadi_int* sp, casadi_real* w) {
    casadi_int i;
    for (i=0; i<nrhs;++i) {
      if (casadi_lsqr_single_solve(A, x+i*sp[1], tr, sp, w)) return 1;
    }
    return 0;
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[208] = 
  {41, 41, 0, 2, 5, 9, 14, 18,
  22, 26, 30, 34, 38, 42, 46, 50,
  54, 58, 62, 66, 70, 74, 78, 82,
  86, 90, 94, 98, 102, 106, 110, 114,
  118, 122, 126, 130, 134, 138, 142, 146,
  152, 157, 161, 164, 0, 1, 0, 1,
  2, 0, 1, 2, 3, 0, 1, 2,
  3, 4, 2, 3, 4, 5, 3, 4,
  5, 6, 4, 5, 6, 7, 5, 6,
  7, 8, 6, 7, 8, 9, 7, 8,
  9, 10, 8, 9, 10, 11, 9, 10,
  11, 12, 10, 11, 12, 13, 11, 12,
  13, 14, 12, 13, 14, 15, 13, 14,
  15, 16, 14, 15, 16, 17, 15, 16,
  17, 18, 16, 17, 18, 19, 17, 18,
  19, 20, 18, 19, 20, 21, 19, 20,
  21, 22, 20, 21, 22, 23, 21, 22,
  23, 24, 22, 23, 24, 25, 23, 24,
  25, 26, 24, 25, 26, 27, 25, 26,
  27, 28, 26, 27, 28, 29, 27, 28,
  29, 30, 28, 29, 30, 31, 29, 30,
  31, 32, 30, 31, 32, 33, 31, 32,
  33, 34, 32, 33, 34, 35, 33, 34,
  35, 36, 34, 35, 36, 37, 35, 36,
  37, 38, 39, 40, 36, 37, 38, 39,
  40, 37, 38, 39, 40, 38, 39, 40};
static const casadi_int casadi_s1[2] = {0, 45};
static const casadi_int casadi_s2[1] = {3};
static const casadi_int casadi_s3[1] = {1};
static const casadi_int casadi_s4[1] = {0};
static const casadi_int casadi_s5[3] = {13, 1, 1};
static const casadi_int casadi_s6[3] = {7, 1, 1};
static const casadi_int casadi_s7[3] = {0, 1, 1};
static const casadi_int casadi_s8[3] = {0, 0, 1};
static const casadi_int casadi_s9[3] = {213, 1, 1};
static const casadi_int casadi_s10[3] = {16, 1, 1};

static const casadi_real casadi_c0[164] = 
  {1., 1.2500000000000000e-01, 0., 5.1388888888888895e-01, 1.1111111111111113e-01, 0., 3.1944444444444442e-01, 5.5555555555555558e-01,
  1.2499999999999993e-01, 0., 4.1666666666666664e-02, 3.3333333333333331e-01, 7.0833333333333326e-01, 1.6666666666666663e-01, 0., 1.6666666666666677e-01,
  6.6666666666666674e-01, 1.6666666666666685e-01, 0., 1.6666666666666660e-01, 6.6666666666666652e-01, 1.6666666666666652e-01, 0., 1.6666666666666652e-01,
  6.6666666666666652e-01, 1.6666666666666660e-01, 0., 1.6666666666666685e-01, 6.6666666666666674e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01,
  6.6666666666666663e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01, 6.6666666666666674e-01, 1.6666666666666685e-01, 0., 1.6666666666666660e-01,
  6.6666666666666663e-01, 1.6666666666666674e-01, 0., 1.6666666666666646e-01, 6.6666666666666652e-01, 1.6666666666666624e-01, 0., 1.6666666666666680e-01,
  6.6666666666666674e-01, 1.6666666666666696e-01, 0., 1.6666666666666696e-01, 6.6666666666666674e-01, 1.6666666666666635e-01, 0., 1.6666666666666635e-01,
  6.6666666666666674e-01, 1.6666666666666696e-01, 0., 1.6666666666666696e-01, 6.6666666666666674e-01, 1.6666666666666680e-01, 0., 1.6666666666666624e-01,
  6.6666666666666641e-01, 1.6666666666666624e-01, 0., 1.6666666666666680e-01, 6.6666666666666674e-01, 1.6666666666666696e-01, 0., 1.6666666666666696e-01,
  6.6666666666666674e-01, 1.6666666666666635e-01, 0., 1.6666666666666635e-01, 6.6666666666666674e-01, 1.6666666666666696e-01, 0., 1.6666666666666696e-01,
  6.6666666666666674e-01, 1.6666666666666680e-01, 0., 1.6666666666666624e-01, 6.6666666666666652e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01,
  6.6666666666666663e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01, 6.6666666666666641e-01, 1.6666666666666580e-01, 0., 1.6666666666666691e-01,
  6.6666666666666696e-01, 1.6666666666666730e-01, 0., 1.6666666666666730e-01, 6.6666666666666696e-01, 1.6666666666666691e-01, 0., 1.6666666666666580e-01,
  6.6666666666666641e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01, 6.6666666666666663e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01,
  6.6666666666666641e-01, 1.6666666666666580e-01, 0., 1.6666666666666691e-01, 6.6666666666666696e-01, 1.6666666666666730e-01, 0., 1.6666666666666730e-01,
  6.6666666666666696e-01, 1.6666666666666691e-01, 0., 1.6666666666666580e-01, 6.6666666666666641e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01,
  6.6666666666666663e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01, 6.6666666666666641e-01, 1.6666666666666580e-01, 0., 1.6666666666666691e-01,
  6.6666666666666696e-01, 1.6666666666666730e-01, 0., 1.6666666666666730e-01, 6.6666666666666696e-01, 1.6666666666666691e-01, 0., 1.6666666666666580e-01,
  6.6666666666666641e-01, 1.6666666666666666e-01, 0., 1.6666666666666666e-01, 7.0833333333333315e-01, 3.3333333333333270e-01, 4.1666666666666310e-02, 0.,
  0., 1.2500000000000014e-01, 5.5555555555555591e-01, 3.1944444444444325e-01, 0., 0., 1.1111111111111142e-01, 5.1388888888888951e-01,
  0., 0., 1.2500000000000083e-01, 1.};
static const casadi_real casadi_c1[45] = 
  {0., 0., 0., 0., 5.0000000000000003e-02, 7.5000000000000011e-02, 1.0000000000000001e-01, 1.2500000000000000e-01,
  1.5000000000000002e-01, 1.7500000000000002e-01, 2.0000000000000001e-01, 2.2500000000000001e-01, 2.5000000000000000e-01, 2.7500000000000002e-01, 3.0000000000000004e-01, 3.2500000000000001e-01,
  3.5000000000000003e-01, 3.7500000000000000e-01, 4.0000000000000002e-01, 4.2500000000000004e-01, 4.5000000000000001e-01, 4.7500000000000003e-01, 5.0000000000000000e-01, 5.2500000000000002e-01,
  5.5000000000000004e-01, 5.7500000000000007e-01, 6.0000000000000009e-01, 6.2500000000000000e-01, 6.5000000000000002e-01, 6.7500000000000004e-01, 7.0000000000000007e-01, 7.2500000000000009e-01,
  7.5000000000000000e-01, 7.7500000000000002e-01, 8.0000000000000004e-01, 8.2500000000000007e-01, 8.5000000000000009e-01, 8.7500000000000000e-01, 9.0000000000000002e-01, 9.2500000000000004e-01,
  9.5000000000000007e-01, 1., 1., 1., 1.};

static const casadi_real casadi_zeros[41] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* mpcc_ch:(x,c[41])->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, *w1=w+42, w3;
  const casadi_real *ss, *wr1, *wr2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  wr1 = arg[1] ? arg[1] : casadi_zeros;
  /* #2: @2 = sparse: 41-by-41, 164 nnz
   (0, 0) -> 1
   (1, 0) -> 0.125
   (0, 1) -> 0
   (1, 1) -> 0.513889
   (2, 1) -> 0.111111
   (0, 2) -> 0
   (1, 2) -> 0.319444
   (2, 2) -> 0.555556
   (3, 2) -> 0.125
   (0, 3) -> 0
   (1, 3) -> 0.0416667
   (2, 3) -> 0.333333
   (3, 3) -> 0.708333
   (4, 3) -> 0.166667
   (2, 4) -> 0
   (3, 4) -> 0.166667
   (4, 4) -> 0.666667
   (5, 4) -> 0.166667
   (3, 5) -> 0
   (4, 5) -> 0.166667
   (5, 5) -> 0.666667
   (6, 5) -> 0.166667
   (4, 6) -> 0
   (5, 6) -> 0.166667
   (6, 6) -> 0.666667
   (7, 6) -> 0.166667
   (5, 7) -> 0
   (6, 7) -> 0.166667
   (7, 7) -> 0.666667
   (8, 7) -> 0.166667
   (6, 8) -> 0
   (7, 8) -> 0.166667
   (8, 8) -> 0.666667
   (9, 8) -> 0.166667
   (7, 9) -> 0
   (8, 9) -> 0.166667
   (9, 9) -> 0.666667
   (10, 9) -> 0.166667
   (8, 10) -> 0
   (9, 10) -> 0.166667
   (10, 10) -> 0.666667
   (11, 10) -> 0.166667
   (9, 11) -> 0
   (10, 11) -> 0.166667
   (11, 11) -> 0.666667
   (12, 11) -> 0.166667
   (10, 12) -> 0
   (11, 12) -> 0.166667
   (12, 12) -> 0.666667
   (13, 12) -> 0.166667
   (11, 13) -> 0
   (12, 13) -> 0.166667
   (13, 13) -> 0.666667
   (14, 13) -> 0.166667
   (12, 14) -> 0
   (13, 14) -> 0.166667
   (14, 14) -> 0.666667
   (15, 14) -> 0.166667
   (13, 15) -> 0
   (14, 15) -> 0.166667
   (15, 15) -> 0.666667
   (16, 15) -> 0.166667
   (14, 16) -> 0
   (15, 16) -> 0.166667
   (16, 16) -> 0.666667
   (17, 16) -> 0.166667
   (15, 17) -> 0
   (16, 17) -> 0.166667
   (17, 17) -> 0.666667
   (18, 17) -> 0.166667
   (16, 18) -> 0
   (17, 18) -> 0.166667
   (18, 18) -> 0.666667
   (19, 18) -> 0.166667
   (17, 19) -> 0
   (18, 19) -> 0.166667
   (19, 19) -> 0.666667
   (20, 19) -> 0.166667
   (18, 20) -> 0
   (19, 20) -> 0.166667
   (20, 20) -> 0.666667
   (21, 20) -> 0.166667
   (19, 21) -> 0
   (20, 21) -> 0.166667
   (21, 21) -> 0.666667
   (22, 21) -> 0.166667
   (20, 22) -> 0
   (21, 22) -> 0.166667
   (22, 22) -> 0.666667
   (23, 22) -> 0.166667
   (21, 23) -> 0
   (22, 23) -> 0.166667
   (23, 23) -> 0.666667
   (24, 23) -> 0.166667
   (22, 24) -> 0
   (23, 24) -> 0.166667
   (24, 24) -> 0.666667
   (25, 24) -> 0.166667
   (23, 25) -> 0
   (24, 25) -> 0.166667
   (25, 25) -> 0.666667
   (26, 25) -> 0.166667
   (24, 26) -> 0
   (25, 26) -> 0.166667
   (26, 26) -> 0.666667
   (27, 26) -> 0.166667
   (25, 27) -> 0
   (26, 27) -> 0.166667
   (27, 27) -> 0.666667
   (28, 27) -> 0.166667
   (26, 28) -> 0
   (27, 28) -> 0.166667
   (28, 28) -> 0.666667
   (29, 28) -> 0.166667
   (27, 29) -> 0
   (28, 29) -> 0.166667
   (29, 29) -> 0.666667
   (30, 29) -> 0.166667
   (28, 30) -> 0
   (29, 30) -> 0.166667
   (30, 30) -> 0.666667
   (31, 30) -> 0.166667
   (29, 31) -> 0
   (30, 31) -> 0.166667
   (31, 31) -> 0.666667
   (32, 31) -> 0.166667
   (30, 32) -> 0
   (31, 32) -> 0.166667
   (32, 32) -> 0.666667
   (33, 32) -> 0.166667
   (31, 33) -> 0
   (32, 33) -> 0.166667
   (33, 33) -> 0.666667
   (34, 33) -> 0.166667
   (32, 34) -> 0
   (33, 34) -> 0.166667
   (34, 34) -> 0.666667
   (35, 34) -> 0.166667
   (33, 35) -> 0
   (34, 35) -> 0.166667
   (35, 35) -> 0.666667
   (36, 35) -> 0.166667
   (34, 36) -> 0
   (35, 36) -> 0.166667
   (36, 36) -> 0.666667
   (37, 36) -> 0.166667
   (35, 37) -> 0
   (36, 37) -> 0.166667
   (37, 37) -> 0.708333
   (38, 37) -> 0.333333
   (39, 37) -> 0.0416667
   (40, 37) -> 0
   (36, 38) -> 0
   (37, 38) -> 0.125
   (38, 38) -> 0.555556
   (39, 38) -> 0.319444
   (40, 38) -> 0
   (37, 39) -> 0
   (38, 39) -> 0.111111
   (39, 39) -> 0.513889
   (40, 39) -> 0
   (38, 40) -> 0
   (39, 40) -> 0.125
   (40, 40) -> 1 */
  wr2 = casadi_c0;
  /* #3: @1 = (@2\@1) */
  rr = w1;
  ss = wr2;
  casadi_copy(wr1, 41, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real w[205];
    casadi_lsqr_solve(ss, rr, 1, 0, casadi_s0, w);
  }
  /* #4: @1 = @1' */
  /* #5: @3 = BSplineParametric(@0, @1) */
  casadi_clear((&w3), 1);
  CASADI_PREFIX(nd_boor_eval)((&w3),1,casadi_c1,casadi_s1,casadi_s2,casadi_s3,w1,1,(&w0),casadi_s4, iw, w);
  /* #6: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

/* mpcc_heavy_gripper_cost_y_0_fun:(i0[13],i1[7],i2[0],i3[],i4[213])->(o0[16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  a00=arg[0]? arg[0][12] : 0;
  a01=arg[4]? arg[4][6] : 0;
  a02=2.5000000000000000e-01;
  a03=(a01-a02);
  a04=(a00-a03);
  a05=arg[4]? arg[4][7] : 0;
  a05=(a04/a05);
  a06=0.;
  a05=casadi_fmax(a05,a06);
  a06=1.;
  a05=casadi_fmin(a05,a06);
  arg[5]=w+0;
  arg[6] = arg[4]? arg[4] + 131 : 0;
  res[1]=w+42;
  w[0] = a05;
  if (casadi_f1(arg+5, res+1, iw, w+43, 0)) return 1;
  a06 = w[42];
  arg[5]=w+0;
  arg[6] = arg[4]? arg[4] + 90 : 0;
  res[1]=w+42;
  w[0] = a05;
  if (casadi_f1(arg+5, res+1, iw, w+43, 0)) return 1;
  a07 = w[42];
  a08=casadi_sq(a07);
  a09=casadi_sq(a06);
  a08=(a08+a09);
  a09=1.0000000000000001e-09;
  a08=(a08+a09);
  a08=sqrt(a08);
  a06=(a06/a08);
  a09=arg[0]? arg[0][0] : 0;
  arg[5]=w+0;
  arg[6] = arg[4]? arg[4] + 8 : 0;
  res[1]=w+42;
  w[0] = a05;
  if (casadi_f1(arg+5, res+1, iw, w+43, 0)) return 1;
  a10 = w[42];
  a09=(a09-a10);
  a10=(a06*a09);
  a07=(a07/a08);
  a08=arg[0]? arg[0][1] : 0;
  arg[5]=w+0;
  arg[6] = arg[4]? arg[4] + 49 : 0;
  res[1]=w+42;
  w[0] = a05;
  if (casadi_f1(arg+5, res+1, iw, w+43, 0)) return 1;
  a11 = w[42];
  a08=(a08-a11);
  a11=(a07*a08);
  a10=(a10-a11);
  if (res[0]!=0) res[0][0]=a10;
  a07=(a07*a09);
  a06=(a06*a08);
  a07=(a07+a06);
  a07=(-a07);
  if (res[0]!=0) res[0][1]=a07;
  a07=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a07;
  a07=arg[0]? arg[0][5] : 0;
  arg[5]=w+0;
  arg[6] = arg[4]? arg[4] + 172 : 0;
  res[1]=w+42;
  w[0] = a05;
  if (casadi_f1(arg+5, res+1, iw, w+43, 0)) return 1;
  a05 = w[42];
  a07=(a07-a05);
  if (res[0]!=0) res[0][3]=a07;
  a07=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][4]=a07;
  a07=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][5]=a07;
  a07=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][6]=a07;
  a07=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][7]=a07;
  a07=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][8]=a07;
  a07=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][9]=a07;
  a07=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][10]=a07;
  a07=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][11]=a07;
  a07=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][12]=a07;
  a07=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][13]=a07;
  a07=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][14]=a07;
  a07=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][15]=a07;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpcc_heavy_gripper_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpcc_heavy_gripper_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mpcc_heavy_gripper_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mpcc_heavy_gripper_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_heavy_gripper_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_heavy_gripper_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_heavy_gripper_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_heavy_gripper_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 292;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_heavy_gripper_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 8*sizeof(casadi_int);
  if (sz_w) *sz_w = 292*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
